// 源/waw_style_copy_-__4w0mnt/src/screens/Screen/Screen.tsx
import { ChevronDownIcon } from "lucide-react";
import React from "react";
import { Badge } from "../../components/ui/badge";
import { GallerySection } from "./sections/GallerySection";
import { ProfileSection } from "./sections/ProfileSection";

export const Screen = (): JSX.Element => {
  return (
    <main
      className="bg-[#f2f2f2] w-full min-w-[375px] min-h-screen relative pb-24"
      data-model-id="15:1887"
    >
      <div className="absolute top-0 left-0 w-full min-h-full bg-[#f6f6f6] -z-10" />

      <header className="absolute top-0 left-[-3.69%] w-[102.45%] h-[44px] flex translate-y-[-1rem] animate-fade-in opacity-0">
        <div className="flex-1 w-[384.17px] flex">
          <div className="flex-1 w-[384.17px] relative">
            <img
              className="absolute w-[6.35%] h-[23.48%] top-[39.39%] left-[89.60%]"
              alt="Battery"
              src="https://c.animaapp.com/mi4v97d2OSuz2g/img/battery.png"
            />

            <img
              className="absolute w-[4.07%] h-[24.92%] top-[39.39%] left-[84.19%]"
              alt="Wifi"
              src="https://c.animaapp.com/mi4v97d2OSuz2g/img/wifi.svg"
            />

            <img
              className="absolute w-[4.53%] h-[24.24%] top-[40.15%] left-[78.31%]"
              alt="Cellular connection"
              src="https://c.animaapp.com/mi4v97d2OSuz2g/img/cellular-connection.svg"
            />

            <time className="absolute w-[7.99%] h-[38.64%] top-[35.23%] left-[9.11%] flex">
              <span className="flex-1 w-[28.69px] [font-family:'Inter',Helvetica] font-normal text-[#333333] text-sm tracking-[0] leading-[normal]">
                9:41
              </span>
            </time>
          </div>
        </div>
      </header>

      <img
        className="absolute top-[31px] left-[247px] w-32 h-[72px] translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:200ms]"
        alt="Group"
        src="https://c.animaapp.com/mi4v97d2OSuz2g/img/group-7.png"
      />

      <Badge className="absolute top-[52px] left-[77px] w-[181px] h-[30px] bg-white rounded-[26px] px-3 py-1 hover:bg-white translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:400ms]">
        <div className="inline-flex items-center gap-2 w-full">
          <div className="inline-flex items-center gap-[3px]">
            <span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#333333] text-[11px] text-center tracking-[0] leading-[normal]">
              成都市
            </span>

            <ChevronDownIcon className="w-[7px] h-[7px] text-[#333333]" />
          </div>

          <img
            className="w-px h-[15px]"
            alt="Divider"
            src="https://c.animaapp.com/mi4v97d2OSuz2g/img/vector-14.svg"
          />

          <div className="inline-flex items-center gap-0.5">
            <img
              className="w-[18px] h-[18px]"
              alt="Designer icon"
              src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-3.svg"
            />

            <span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#a6a6a6] text-[11px] text-center tracking-[0] leading-[normal]">
              设计师
            </span>
          </div>
        </div>
      </Badge>

      <img
        className="absolute top-[59px] left-[15px] w-[52px] h-[15px] object-cover translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:600ms]"
        alt="Logo"
        src="https://c.animaapp.com/mi4v97d2OSuz2g/img/image-23.png"
      />

      <div className="relative w-full flex flex-col">
        <section className="w-full max-w-[375px] mx-auto translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:800ms] mt-[90px]">
          <div className="w-full h-[187px] bg-white rounded-md relative">
            <div className="w-full h-[188px]">
              <h1 className="absolute top-4 left-0 w-full [font-family:'DIN_BlackAlternate-Regular',Helvetica] font-normal text-[#333333] text-[75px] text-center tracking-[0] leading-[normal] whitespace-nowrap">
                WAW style
              </h1>

              <img
                className="absolute top-0 left-0 w-full h-[188px]"
                alt="Profile background"
                src="https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-177.png"
              />

              <div className="absolute top-[156px] left-0 w-full h-8 bg-[#ffffff3b] backdrop-blur-[10.55px] backdrop-brightness-[100%] [-webkit-backdrop-filter:blur(10.55px)_brightness(100%)]" />
            </div>
          </div>
        </section>

        <div className="w-full max-w-[375px] mx-auto mt-2">
          <ProfileSection />
        </div>
      </div>
      <GallerySection />
    </main>
  );
};

// 源/index/src/screens/Screen.vue
<template>
  <div class="screen" data-model-id="1:10883">
    <div class="rectangle" />
    <img class="rectangle-2" alt="Rectangle" src="/img/rectangle-186.png" />
    <div class="rectangle-3" />
    <div class="element">
      <div class="iphone-x-status-bars-wrapper">
        <div class="iphone-x-status-bars">
          <div class="battery">
            <img class="border" alt="Border" src="/img/border.svg" />
            <img class="cap" alt="Cap" src="/img/cap.svg" />
            <img class="capacity" alt="Capacity" src="/img/capacity.svg" />
          </div>
          <img class="wifi" alt="Wifi" src="/img/wifi.svg" />
          <img class="cellular-connection" alt="Cellular connection" src="/img/cellular-connection.svg" />
          <div class="time-style">
            <div class="text-wrapper-17">9:41</div>
          </div>
        </div>
      </div>
    </div>
    <div class="group">
      <img class="vector-31" alt="Vector" src="/img/vector-13.svg" />
      <div class="ellipse-3" />
      <div class="ellipse-4" />
      <div class="ellipse-5" />
      <div class="ellipse-6" />
      <div class="ellipse-7" />
    </div>
    <FrameSubsection />
    <FrameWrapperSubsection />
    <img class="frame-25" alt="Frame" src="/img/frame-1881.svg" />
    <img class="subtract-2" alt="Subtract" src="/img/subtract-1.svg" />
    <DivWrapperSubsection />
    <DivSubsection />
  </div>
</template>

<script>
import DivSubsection from "./Screen/sections/DivSubsection.vue";
import DivWrapperSubsection from "./Screen/sections/DivWrapperSubsection.vue";
import FrameSubsection from "./Screen/sections/FrameSubsection.vue";
import FrameWrapperSubsection from "./Screen/sections/FrameWrapperSubsection.vue";

export default {
  name: "Screen",
  components: {
    DivSubsection,
    DivWrapperSubsection,
    FrameSubsection,
    FrameWrapperSubsection,
  },
};
</script>

<style>
.screen {
  background-color: #f2f2f2;
  min-height: 892px;
  min-width: 375px;
  overflow: hidden;
  position: relative;
  width: 100%;
}

.screen .rectangle {
  background-color: var(--variable-collection);
  height: 812px;
  left: 0;
  position: absolute;
  top: 0;
  width: 375px;
}

.screen .rectangle-2 {
  height: 300px;
  left: 0;
  position: absolute;
  top: 0;
  width: 375px;
}

.screen .rectangle-3 {
  background-color: #f3f3f3;
  border-radius: 8px 8px 0px 0px;
  height: 522px;
  left: calc(50.00% - 188px);
  position: absolute;
  top: 290px;
  width: 375px;
}

.screen .element {
  align-items: flex-start;
  display: flex;
  height: 44px;
  left: -14px;
  min-width: 384px;
  position: absolute;
  top: 1px;
}

.screen .iphone-x-status-bars-wrapper {
  display: flex;
  height: 44px;
  width: 384px;
}

.screen .iphone-x-status-bars {
  background-image: url(../../static/img/rectangle.svg);
  background-size: 100% 100%;
  flex: 1;
  position: relative;
  width: 384.17px;
}

.screen .battery {
  height: 23.48%;
  left: 89.73%;
  position: absolute;
  top: 40.53%;
  width: 6.35%;
}

.screen .border {
  height: 100%;
  left: -2.05%;
  position: absolute;
  top: -4.84%;
  width: 88.13%;
}

.screen .cap {
  height: 38.71%;
  left: 94.43%;
  position: absolute;
  top: 30.65%;
  width: 5.57%;
}

.screen .capacity {
  height: 70.97%;
  left: 6.30%;
  position: absolute;
  top: 14.52%;
  width: 75.54%;
}

.screen .wifi {
  height: 24.92%;
  left: 84.18%;
  position: absolute;
  top: 39.39%;
  width: 4.07%;
}

.screen .cellular-connection {
  height: 24.24%;
  left: 78.31%;
  position: absolute;
  top: 40.15%;
  width: 4.53%;
}

.screen .time-style {
  display: flex;
  height: 38.64%;
  left: 9.11%;
  position: absolute;
  top: 35.23%;
  width: 7.99%;
}

.screen .text-wrapper-17 {
  color: #333333;
  flex: 1;
  font-family: "Inter", Helvetica;
  font-size: 14px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  width: 28.69px;
}

.screen .group {
  background-color: #ffffff80;
  border-radius: 17px;
  box-shadow: 0px 0px 22.1px #0000000f;
  height: 28px;
  left: 269px;
  position: absolute;
  top: 53px;
  width: 86px;
}

.screen .vector-31 {
  height: 18px;
  left: 42px;
  position: absolute;
  top: 6px;
  width: 1px;
}

.screen .ellipse-3 {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 16px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.screen .ellipse-4 {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 30px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.screen .ellipse-5 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 22px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.screen .ellipse-6 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 61px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.screen .ellipse-7 {
  border: 1px solid;
  border-color: #000000;
  border-radius: 8px;
  height: 16px;
  left: 56px;
  position: absolute;
  top: 6px;
  width: 16px;
}

.screen .frame-25 {
  height: 30px;
  left: 15px;
  position: absolute;
  top: 51px;
  width: 69px;
}

.screen .subtract-2 {
  height: 224px;
  left: calc(50.00% - 178px);
  position: absolute;
  top: 260px;
  width: 355px;
}
</style>
