// 源/waw_style_copy_-_-_5epqgd/src/screens/DivWrapper/DivWrapper.tsx
import { ChevronLeftIcon } from "lucide-react";
import React from "react";
import { Button } from "../../components/ui/button";
import { ProfileSection } from "./sections/ProfileSection";
import { ServicesSection } from "./sections/ServicesSection";

export const DivWrapper = (): JSX.Element => {
  const statusBarIcons = [
    {
      className: "absolute w-[6.35%] h-[23.48%] top-[39.39%] left-[89.60%]",
      alt: "Battery",
      src: "https://c.animaapp.com/mi5eklbiAEaKLJ/img/battery.png",
    },
    {
      className: "absolute w-[4.07%] h-[24.92%] top-[39.39%] left-[84.18%]",
      alt: "Wifi",
      src: "https://c.animaapp.com/mi5eklbiAEaKLJ/img/wifi.svg",
    },
    {
      className: "absolute w-[4.53%] h-[24.24%] top-[40.15%] left-[78.31%]",
      alt: "Cellular connection",
      src: "https://c.animaapp.com/mi5eklbiAEaKLJ/img/cellular-connection.svg",
    },
  ];

  return (
    <div
      className="bg-[#f2f2f2] overflow-hidden w-full min-w-[375px] relative flex flex-col"
      data-model-id="15:7551"
    >
      <header className="relative w-full bg-white z-10">
        <nav className="w-full h-[126px] relative">
          <div className="absolute w-[102.45%] h-[44px] top-0 left-[-3.69%] flex">
            <div className="flex-1 w-[384.17px] flex">
              <div className="flex-1 w-[384.17px] relative bg-[100%_100%]">
                {statusBarIcons.map((icon, index) => (
                  <img
                    key={`status-icon-${index}`}
                    className={icon.className}
                    alt={icon.alt}
                    src={icon.src}
                  />
                ))}

                <div className="absolute w-[7.99%] h-[38.64%] top-[35.23%] left-[9.11%] flex">
                  <div className="flex-1 w-[28.69px] [font-family:'Inter',Helvetica] font-normal text-black text-sm tracking-[0] leading-[normal]">
                    9:41
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="absolute top-[58px] left-[15px] flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              className="h-auto w-4 p-0 hover:bg-transparent"
              aria-label="Go back"
            >
              <ChevronLeftIcon className="w-4 h-4" />
            </Button>
          </div>

          <img
            className="absolute top-[31px] right-[15px] w-32 h-[72px]"
            alt="Logo"
            src="https://c.animaapp.com/mi5eklbiAEaKLJ/img/group-8.png"
          />

          <div className="absolute top-[58px] right-[15px] flex items-center gap-2">
            <Button
              variant="ghost"
              size="icon"
              className="h-auto w-4 p-0 hover:bg-transparent"
              aria-label="Share"
            >
              <img
                className="w-4 h-4"
                alt="Share"
                src="https://c.animaapp.com/mi5eklbiAEaKLJ/img/frame-1.svg"
              />
            </Button>
          </div>
        </nav>
      </header>

      <main className="relative w-full flex-1 flex flex-col">
        <ProfileSection />
        <ServicesSection />
      </main>

      <footer className="flex flex-col w-full items-center justify-end gap-2.5 px-[120px] py-2 relative">
        <div className="relative w-[134px] h-[5px] bg-black rounded-[100px]" />
      </footer>
    </div>
  );
};

// 源/资产2/src/screens/DivWrapper.vue
<template>
  <div class="div-wrapper" data-model-id="32:4861">
    <div class="rectangle-2" />
    <div class="vector-wrapper">
      <img class="img" alt="Vector" src="/img/vector.svg" />
    </div>
    <div class="element">
      <div class="iphone-x-status-bars-wrapper">
        <div class="iphone-x-status-bars">
          <div class="battery">
            <img class="border" alt="Border" src="/img/border.svg" />
            <img class="cap" alt="Cap" src="/img/cap.svg" />
            <img class="capacity" alt="Capacity" src="/img/capacity.svg" />
          </div>
          <img class="wifi" alt="Wifi" src="/img/wifi.svg" />
          <img class="cellular-connection" alt="Cellular connection" src="/img/cellular-connection.svg" />
          <div class="time-style">
            <div class="text-wrapper-4">9:41</div>
          </div>
        </div>
      </div>
    </div>
    <div class="group">
      <img class="vector-2" alt="Vector" src="/img/vector-13.svg" />
      <div class="ellipse" />
      <div class="ellipse-2" />
      <div class="ellipse-3" />
      <div class="ellipse-4" />
      <div class="ellipse-5" />
    </div>
    <div class="frame-wrapper">
      <div class="frame-2">
        <div class="frame-3">
          <div class="frame-4">
            <div class="frame-5">
              <div class="text-wrapper-5">总资产(元)</div>
            </div>
          </div>
        </div>
        <div class="text-wrapper-6">6666.66</div>
      </div>
    </div>
    <div class="home-indicator-wrapper">
      <div class="home-indicator" />
    </div>
    <div class="frame-6">
      <div class="frame-7">
        <div class="home-indicator" />
      </div>
    </div>
    <div class="text-wrapper-7">我的资产</div>
    <div class="frame-8">
      <div class="frame-9">
        <div class="text-wrapper-8">本月</div>
        <div class="img-wrapper">
          <img class="vector-3" alt="Vector" src="/img/vector-1.svg" />
        </div>
      </div>
      <div class="frame-10">
        <Frame class="frame-2360" />
        <Frame class="frame-2360" />
        <Frame class="frame-2360" />
        <div class="frame-11">
          <div class="frame-12">
            <img class="rectangle-3" alt="Rectangle" src="/img/rectangle-169.png" />
            <div class="frame-13">
              <div class="frame-14">
                <div class="text-wrapper-9">成都美发沙龙</div>
                <div class="text-wrapper-10">洗剪吹</div>
                <div class="text-wrapper-10">今天 10:50</div>
              </div>
              <div class="text-wrapper-11">+100</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Frame from "../components/Frame.vue";

export default {
  name: "DivWrapper",
  components: {
    Frame
  }
};
</script>

<style>
.div-wrapper {
  background-color: #f2f2f2;
  min-height: 812px;
  min-width: 375px;
  overflow: hidden;
  position: relative;
  width: 100%;
}

.div-wrapper .rectangle-2 {
  background-color: #ffffff;
  height: 88px;
  left: 0;
  position: absolute;
  top: 0;
  width: 375px;
}

.div-wrapper .vector-wrapper {
  height: 16px;
  left: 15px;
  position: absolute;
  top: 58px;
  width: 16px;
}

.div-wrapper .img {
  height: 99.77%;
  left: 14.16%;
  position: absolute;
  top: 0;
  width: 56.08%;
}

.div-wrapper .element {
  align-items: flex-start;
  display: flex;
  height: 44px;
  left: -14px;
  min-width: 384px;
  position: absolute;
  top: 1px;
}

.div-wrapper .iphone-x-status-bars-wrapper {
  display: flex;
  height: 44px;
  width: 384px;
}

.div-wrapper .iphone-x-status-bars {
  background-image: url(../../static/img/rectangle.svg);
  background-size: 100% 100%;
  flex: 1;
  position: relative;
  width: 384.17px;
}

.div-wrapper .battery {
  height: 23.48%;
  left: 89.73%;
  position: absolute;
  top: 40.53%;
  width: 6.35%;
}

.div-wrapper .border {
  height: 100%;
  left: -2.05%;
  position: absolute;
  top: -4.84%;
  width: 88.13%;
}

.div-wrapper .cap {
  height: 38.71%;
  left: 94.43%;
  position: absolute;
  top: 30.64%;
  width: 5.57%;
}

.div-wrapper .capacity {
  height: 70.97%;
  left: 6.30%;
  position: absolute;
  top: 14.52%;
  width: 75.54%;
}

.div-wrapper .wifi {
  height: 24.92%;
  left: 84.18%;
  position: absolute;
  top: 39.39%;
  width: 4.07%;
}

.div-wrapper .cellular-connection {
  height: 24.24%;
  left: 78.31%;
  position: absolute;
  top: 40.15%;
  width: 4.53%;
}

.div-wrapper .time-style {
  display: flex;
  height: 38.64%;
  left: 9.11%;
  position: absolute;
  top: 35.23%;
  width: 7.99%;
}

.div-wrapper .text-wrapper-4 {
  color: #000000;
  flex: 1;
  font-family: "Inter", Helvetica;
  font-size: 14px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  width: 28.69px;
}

.div-wrapper .group {
  background-color: #ffffff80;
  border-radius: 17px;
  box-shadow: 0px 0px 22.1px #0000000f;
  height: 28px;
  left: 269px;
  position: absolute;
  top: 53px;
  width: 86px;
}

.div-wrapper .vector-2 {
  height: 18px;
  left: 42px;
  position: absolute;
  top: 6px;
  width: 1px;
}

.div-wrapper .ellipse {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 16px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.div-wrapper .ellipse-2 {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 30px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.div-wrapper .ellipse-3 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 22px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.div-wrapper .ellipse-4 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 61px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.div-wrapper .ellipse-5 {
  border: 1px solid;
  border-color: #000000;
  border-radius: 8px;
  height: 16px;
  left: 56px;
  position: absolute;
  top: 6px;
  width: 16px;
}

.div-wrapper .frame-wrapper {
  align-items: flex-end;
  background: linear-gradient(
    309deg,
    rgba(135, 134, 145, 1) 0%,
    rgba(59, 54, 83, 1) 100%
  );
  border-radius: 8px;
  display: flex;
  flex-direction: column;
  gap: 3px;
  height: 103px;
  left: calc(50.00% - 178px);
  padding: 5px 16px;
  position: absolute;
  top: 97px;
  width: 355px;
}

.div-wrapper .frame-2 {
  align-items: flex-start;
  align-self: stretch;
  display: flex;
  flex: 0 0 auto;
  flex-direction: column;
  position: relative;
  width: 100%;
}

.div-wrapper .frame-3 {
  align-items: center;
  align-self: stretch;
  display: flex;
  gap: 2px;
  height: 41px;
  position: relative;
  width: 100%;
}

.div-wrapper .frame-4 {
  align-items: flex-start;
  display: inline-flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 2px;
  position: relative;
}

.div-wrapper .frame-5 {
  align-items: center;
  align-self: stretch;
  display: flex;
  flex: 0 0 auto;
  gap: 20px;
  position: relative;
  width: 100%;
}

.div-wrapper .text-wrapper-5 {
  color: #ffffff;
  font-family: "PingFang SC-Semibold", Helvetica;
  font-size: 16px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  margin-top: -1.00px;
  position: relative;
  text-align: center;
  width: fit-content;
}

.div-wrapper .text-wrapper-6 {
  align-self: stretch;
  color: #ffffff;
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 26px;
  font-weight: 500;
  letter-spacing: 0;
  line-height: normal;
  position: relative;
}

.div-wrapper .home-indicator-wrapper {
  align-items: center;
  bottom: 0;
  display: flex;
  flex-direction: column;
  gap: 10px;
  height: 34px;
  justify-content: flex-end;
  left: calc(50.00% - 188px);
  padding: 8px 120px;
  position: absolute;
  width: 375px;
}

.div-wrapper .home-indicator {
  background-color: #000000;
  border-radius: 100px;
  height: 5px;
  position: relative;
  width: 134px;
}

.div-wrapper .frame-6 {
  align-items: flex-start;
  bottom: 0;
  box-shadow: 0px -1px 0px #0000000a;
  display: flex;
  flex-direction: column;
  left: calc(50.00% - 188px);
  position: absolute;
  width: 375px;
}

.div-wrapper .frame-7 {
  align-items: center;
  display: flex;
  flex-direction: column;
  gap: 10px;
  height: 34px;
  justify-content: flex-end;
  padding: 8px 120px;
  position: relative;
  width: 375px;
}

.div-wrapper .text-wrapper-7 {
  color: #333333;
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 16px;
  font-weight: 500;
  left: calc(50.00% - 32px);
  letter-spacing: 0;
  line-height: normal;
  position: absolute;
  text-align: center;
  top: 55px;
}

.div-wrapper .frame-8 {
  align-items: flex-start;
  display: flex;
  flex-direction: column;
  gap: 10px;
  left: 10px;
  position: absolute;
  top: 214px;
  width: 355px;
}

.div-wrapper .frame-9 {
  align-items: center;
  display: inline-flex;
  flex: 0 0 auto;
  gap: 8px;
  position: relative;
}

.div-wrapper .text-wrapper-8 {
  color: #333333;
  font-family: "PingFang SC-Semibold", Helvetica;
  font-size: 15px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  margin-top: -1.00px;
  position: relative;
  text-align: center;
  width: fit-content;
}

.div-wrapper .img-wrapper {
  aspect-ratio: 1;
  height: 10px;
  position: relative;
  width: 10px;
}

.div-wrapper .vector-3 {
  height: 62.38%;
  left: 0;
  position: absolute;
  top: 16.65%;
  width: 96.69%;
}

.div-wrapper .frame-10 {
  align-items: flex-start;
  align-self: stretch;
  background-color: #ffffff;
  border-radius: 6px;
  display: flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 20px;
  justify-content: center;
  padding: 15px 10px;
  position: relative;
  width: 100%;
}

.div-wrapper .frame-2360 {
  align-self: stretch !important;
  flex: 0 0 auto !important;
  left: unset !important;
  top: unset !important;
  width: 100% !important;
}

.div-wrapper .frame-11 {
  align-items: flex-start;
  align-self: stretch;
  display: flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 15px;
  position: relative;
  width: 100%;
}

.div-wrapper .frame-12 {
  align-items: center;
  align-self: stretch;
  display: flex;
  flex: 0 0 auto;
  gap: 8px;
  justify-content: center;
  position: relative;
  width: 100%;
}

.div-wrapper .rectangle-3 {
  aspect-ratio: 1;
  height: 66px;
  position: relative;
  width: 66px;
}

.div-wrapper .frame-13 {
  align-items: center;
  display: flex;
  flex: 1;
  flex-grow: 1;
  justify-content: space-between;
  position: relative;
}

.div-wrapper .frame-14 {
  align-items: flex-start;
  display: inline-flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 3px;
  position: relative;
}

.div-wrapper .text-wrapper-9 {
  color: #666666;
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 14px;
  font-weight: 500;
  letter-spacing: 0;
  line-height: normal;
  margin-top: -1.00px;
  position: relative;
  width: fit-content;
}

.div-wrapper .text-wrapper-10 {
  color: var(--variable-collection-a7a7a7);
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 12px;
  font-weight: 500;
  letter-spacing: 0;
  line-height: normal;
  position: relative;
  width: fit-content;
}

.div-wrapper .text-wrapper-11 {
  color: #333333;
  font-family: "PingFang SC-Semibold", Helvetica;
  font-size: 17px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  position: relative;
  text-align: center;
  width: fit-content;
}
</style>
