// components/index/index/ProfileSection.vue
<template>
	<view class="profile-section">
		<!-- 提示卡片 -->
		<view class="alert-card animate-fade-in" style="animation-delay: 0ms;">
			<view class="alert-content">
				<view class="alert-left">
					<view class="avatar">
						<image class="avatar-img" src="https://c.animaapp.com/mi4v97d2OSuz2g/img/ellipse-71.svg" mode="aspectFill"></image>
					</view>
					<text class="alert-text">hey,快去看看你周边设计师吧！</text>
				</view>
				<view class="close-btn">
					<image class="close-icon" src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-6.svg" mode="aspectFit"></image>
				</view>
			</view>
		</view>
		
		<!-- 快捷操作卡片 -->
		<view class="quick-actions-card animate-fade-in" style="animation-delay: 100ms;">
			<view class="quick-actions-top">
				<view 
					v-for="(action, index) in quickActions" 
					:key="index" 
					class="quick-action-item"
					@tap="handleQuickAction(action, index)"
				>
					<image class="action-icon" :src="action.icon" mode="aspectFit"></image>
					<view class="action-info">
						<text class="action-title">{{ action.title }}</text>
						<text class="action-subtitle">{{ action.subtitle }}</text>
					</view>
				</view>
			</view>
			<view class="quick-actions-bottom">
				<view 
					v-for="(action, index) in bottomActions" 
					:key="index" 
					class="bottom-action-item"
					@tap="handleBottomAction(action, index)"
				>
					<image class="action-icon" :src="action.icon" mode="aspectFit"></image>
					<view class="action-info">
						<text class="action-title-small">{{ action.title }}</text>
						<text class="action-subtitle-small">{{ action.subtitle }}</text>
					</view>
				</view>
			</view>
		</view>
		
		<!-- 作品集 -->
		<view class="portfolio-card animate-fade-in" style="animation-delay: 200ms;">
			<view class="card-header">
				<text class="card-title">作品集</text>
				<image class="more-icon" src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-7.svg" mode="aspectFit"></image>
			</view>
			<view class="portfolio-content">
				<view 
					v-for="(item, index) in portfolioItems" 
					:key="index" 
					class="portfolio-item"
					:style="{ left: index === 0 ? '0' : '314rpx' }"
				>
					<image class="portfolio-img" :src="item.image" mode="aspectFill"></image>
					<image class="portfolio-overlay" :src="item.overlay" mode="aspectFill"></image>
					<image class="portfolio-gradient" :src="item.gradient" mode="aspectFill" :style="{ left: index === 0 ? '0' : '58rpx', width: index === 0 ? '372rpx' : '314rpx' }"></image>
					<view class="portfolio-label" :style="{ left: item.align === 'left' ? '20rpx' : '200rpx' }">
						<text v-if="item.align === 'left'" class="label-text">{{ item.label }}</text>
						<text class="label-count">{{ item.count }}</text>
						<text v-if="item.align === 'right'" class="label-text">{{ item.label }}</text>
					</view>
				</view>
			</view>
		</view>
		
		<!-- 设计师 -->
		<view class="designers-card animate-fade-in" style="animation-delay: 300ms;">
			<view class="card-header" @tap="handleSectionHeaderClick('designer')">
				<text class="card-title">设计师</text>
				<image class="more-icon" src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-7.svg" mode="aspectFit"></image>
			</view>
			<scroll-view class="tabs-scroll" scroll-x>
				<view class="tabs-container">
					<view 
						v-for="(tab, index) in designerTabs" 
						:key="index" 
						class="tab-item"
						:class="{ active: activeDesignerTab === index }"
						@tap="handleDesignerTabClick(index)"
					>
						<text>{{ tab }}</text>
					</view>
				</view>
			</scroll-view>
			<swiper 
				class="designers-swiper"
				:current="designerSwiperIndex"
				@change="handleDesignerSwiperChange"
				:indicator-dots="false"
				:autoplay="false"
				:circular="false"
			>
				<swiper-item 
					v-for="(slide, slideIndex) in designerSlides" 
					:key="slideIndex"
					class="designers-swiper-item"
				>
				<view class="designers-container">
					<view 
							v-for="(designer, index) in slide" 
						:key="index" 
						class="designer-card"
						@tap="handleDesignerClick(designer)"
					>
						<view class="designer-img-wrapper">
							<view class="designer-img-bg"></view>
							<image class="designer-img" :src="designer.image" mode="aspectFill"></image>
						</view>
						<view class="designer-info">
							<view class="designer-header">
								<text class="designer-name">{{ designer.name }}</text>
								<view class="designer-badge secondary">{{ designer.role }}</view>
								<view class="designer-badge primary">{{ designer.level }}</view>
							</view>
							<text class="designer-title">{{ designer.title }}</text>
							<view class="designer-footer">
								<view class="rating-info">
									<text class="rating-score">{{ designer.rating }}</text>
									<text class="star">★</text>
									<text class="review-count">({{ designer.reviews }})</text>
								</view>
								<text class="distance">{{ designer.distance }}</text>
							</view>
						</view>
					</view>
				</view>
				</swiper-item>
			</swiper>
			<view class="pagination-dots">
				<view 
					v-for="(dot, index) in designerSlides.length" 
					:key="index" 
					class="dot"
					:class="{ active: index === designerSwiperIndex }"
					:style="{ width: index === designerSwiperIndex ? '28rpx' : '10rpx' }"
				></view>
			</view>
		</view>
		
		<!-- 品牌馆 -->
		<view class="brands-card animate-fade-in" style="animation-delay: 400ms;">
			<view class="card-header" @tap="handleSectionHeaderClick('brand')">
				<text class="card-title">品牌馆</text>
				<image class="more-icon" src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-7.svg" mode="aspectFit"></image>
			</view>
			<scroll-view class="tabs-scroll" scroll-x>
				<view class="tabs-container">
					<view 
						v-for="(tab, index) in brandTabs" 
						:key="index" 
						class="tab-item"
						:class="{ active: activeBrandTab === tab }"
						@tap="handleBrandTabClick(tab)"
					>
						<text>{{ tab }}</text>
					</view>
				</view>
			</scroll-view>
			<scroll-view class="brands-scroll" scroll-x show-scrollbar="false" scroll-with-animation>
				<view class="brands-container">
					<view 
						v-for="(brand, index) in filteredBrands" 
						:key="index" 
						class="brand-card"
						@tap="handleBrandClick(brand)"
					>
						<view class="brand-img-wrapper">
							<view v-if="!brand.hasOverlay" class="brand-img-bg"></view>
							<image class="brand-img" :src="brand.image" mode="aspectFill"></image>
						</view>
						<view class="brand-info">
							<text class="brand-name">{{ brand.name }}</text>
							<view class="brand-rating">
								<text class="rating-score">{{ brand.rating }}</text>
								<view class="stars">
									<text v-if="brand.hasOverlay" class="star">★</text>
									<text v-if="brand.hasOverlay" class="star">★</text>
									<text v-if="brand.hasOverlay" class="star">★</text>
									<text v-if="!brand.hasOverlay" class="star">★</text>
								</view>
								<text class="review-count">({{ brand.reviews }})</text>
							</view>
							<view class="brand-address">
								<image class="location-icon" src="/static/icon/position.png" mode="aspectFit"></image>
								<text class="address-text">{{ brand.address }}</text>
								<text v-if="brand.distance" class="distance">{{ brand.distance }}</text>
							</view>
						</view>
						<view v-if="brand.hasOverlay" class="brand-overlay"></view>
					</view>
				</view>
			</scroll-view>
		</view>
		
		<!-- 优服务 -->
		<view class="services-section animate-fade-in" style="animation-delay: 500ms;">
			<view class="services-header">
				<text class="services-title" @tap="handleSectionHeaderClick('service')">优服务</text>
				<view class="filter-btn">
					<text class="filter-text">筛选</text>
					<image class="filter-icon" src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-5.svg" mode="aspectFit"></image>
				</view>
			</view>
			<scroll-view class="service-tabs-scroll" scroll-x>
				<view class="service-tabs-container">
					<view 
						v-for="(tab, index) in serviceTabs" 
						:key="index" 
						class="service-tab-item"
					:class="{ active: activeServiceTab === tab }"
					@tap="handleServiceTabClick(tab)"
					>
						<text>{{ tab }}</text>
					<image v-if="activeServiceTab === tab" class="tab-indicator" src="https://c.animaapp.com/mi4v97d2OSuz2g/img/vector-15.svg" mode="aspectFit"></image>
					</view>
				</view>
			</scroll-view>
			<view class="services-grid">
				<view 
					v-for="(service, index) in filteredServices" 
					:key="index" 
					class="service-card"
				>
					<image class="service-img" :src="service.image" mode="aspectFill"></image>
					<view class="service-info">
						<text class="service-title">{{ service.title }}</text>
						<text class="service-desc">{{ service.description }}</text>
						<view class="service-price">
							<text class="price-symbol">¥</text>
							<text class="price-value">{{ service.price }}</text>
						</view>
						<view class="service-footer">
							<view class="service-designer">
								<view class="service-avatar">
									<image class="avatar-img-small" :src="service.avatar" mode="aspectFill"></image>
								</view>
								<view class="designer-details">
									<text class="designer-name-small">{{ service.designerName }}</text>
									<text class="designer-role-small">{{ service.designerRole }}</text>
									<view class="designer-rating">
										<text class="rating-score-small">{{ service.rating }}</text>
										<text class="star-small">★</text>
										<text class="review-count-small">({{ service.reviews }})</text>
									</view>
								</view>
							</view>
							<text class="service-distance">{{ service.distance }}</text>
						</view>
					</view>
				</view>
			</view>
		</view>
	</view>
</template>

<script>
import api from '@/api'

export default {
	data() {
		return {
			loading: false,
			// 快捷操作 - 固定导航入口
			quickActions: [
				{
					icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2284.svg",
					title: "设计师",
					subtitle: "发现宝藏设计师",
				},
				{
					icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2280.svg",
					title: "优服务",
					subtitle: "甄选特色服务",
				},
				{
					icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2278.svg",
					title: "品牌馆",
					subtitle: "优质线下门店",
				},
			],
			// 底部操作 - 固定导航入口
			bottomActions: [
				{
					icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2005.svg",
					title: "预约单",
					subtitle: "你的预约订单",
				},
				{
					icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2006.svg",
					title: "优惠券",
					subtitle: "更多折扣等你",
				},
				{
					icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2007.svg",
					title: "会员",
					subtitle: "VIP平台特权",
				},
				{
					icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2008.svg",
					title: "入驻中",
					subtitle: "诚邀全球设计师",
				},
			],
			// 作品集 - 固定展示区域
			portfolioItems: [
				{
					image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-175.png",
					overlay: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-177-1.svg",
					gradient: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-179.svg",
					label: "WOMAN",
					count: "12,349+",
					align: "left",
				},
				{
					image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-176.png",
					overlay: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-178.svg",
					gradient: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-180.svg",
					label: "MAN",
					count: "12,349+",
					align: "right",
				},
			],
			// 设计师相关
			designerTabs: ["首席创意", "总监店长", "网红名师", "国际导师"],
			activeDesignerTab: 0,
			designerSwiperIndex: 0,
			designersByTab: {}, // 从 mock 数据加载
			// 品牌馆相关
			brandTabs: ["专业店", "品牌店", "工作室", "综合店"],
			activeBrandTab: "专业店",
			allBrands: {}, // 从 mock 数据加载
			// 服务相关
			serviceTabs: ["全部", "洗吹", "剪发", "烫发", "染发", "护发", "头皮", "接发"],
			activeServiceTab: "全部",
			allServices: {}, // 从 mock 数据加载
		}
	},
	computed: {
		filteredServices() {
			// 从 mock 数据获取对应分类的服务
			return this.allServices[this.activeServiceTab] || []
		},
		filteredBrands() {
			return this.allBrands[this.activeBrandTab] || []
		},
		designerSlides() {
			// 根据 tab 索引获取对应分类名
			const tabName = this.designerTabs[this.activeDesignerTab]
			const currentDesigners = this.designersByTab[tabName] || []
			const slides = []
			for (let i = 0; i < currentDesigners.length; i += 2) {
				slides.push(currentDesigners.slice(i, i + 2))
			}
			return slides
		}
	},
	mounted() {
		this.fetchHomeData()
	},
	methods: {
		// 获取首页数据
		async fetchHomeData() {
			if (this.loading) return
			this.loading = true
			try {
				const res = await api.common.getHomeData()
				if (res.code === 0) {
					const data = res.data
					// 更新设计师数据 - mock返回的是 designersByCategory
					if (data.designersByCategory) {
						this.designersByTab = data.designersByCategory
					}
					// 更新品牌馆数据 - mock返回的是 brandsByCategory
					if (data.brandsByCategory) {
						this.allBrands = data.brandsByCategory
					}
					// 更新服务数据 - mock返回的是 servicesByCategory
					if (data.servicesByCategory) {
						this.allServices = data.servicesByCategory
					}
				}
			} catch (err) {
				console.error('获取首页数据失败:', err)
			} finally {
				this.loading = false
			}
		},
		handleQuickAction(action, index) {
			let url = ''
			if (action.title === '设计师') {
				url = '/pages/main/index?tab=designer'
			} else if (action.title === '优服务') {
				url = '/pages/main/index?tab=service'
			} else if (action.title === '品牌馆') {
				url = '/pages/main/index?tab=brand'
			}
			
			if (url) {
				console.log('准备跳转到:', url)
				uni.navigateTo({
					url: url,
					success: (res) => {
						console.log('跳转成功:', res)
					},
					fail: (err) => {
						console.error('跳转失败:', err)
						uni.showToast({
							title: '跳转失败: ' + (err.errMsg || '未知错误'),
							icon: 'none',
							duration: 2000
						})
					}
				})
			}
		},
		handleSectionHeaderClick(section) {
			// 点击卡片标题跳转到 main 页面对应的标签
			let url = ''
			if (section === 'designer') {
				url = '/pages/main/index?tab=designer'
			} else if (section === 'service') {
				url = '/pages/main/index?tab=service'
			} else if (section === 'brand') {
				url = '/pages/main/index?tab=brand'
			}
			
			if (url) {
				console.log('准备跳转到:', url)
				uni.navigateTo({
					url: url,
					success: (res) => {
						console.log('跳转成功:', res)
					},
					fail: (err) => {
						console.error('跳转失败:', err)
						uni.showToast({
							title: '跳转失败: ' + (err.errMsg || '未知错误'),
							icon: 'none',
							duration: 2000
						})
					}
				})
			}
		},
		handleServiceTabClick(tab) {
			// 切换服务筛选项
			this.activeServiceTab = tab
		},
		handleDesignerClick(designer) {
			// 跳转到设计师详情页面，传递设计师ID等信息
			uni.navigateTo({
				url: `/pages/designer/detail?id=${designer.id || 1}&name=${encodeURIComponent(designer.name || '')}`
			})
		},
		handleDesignerSwiperChange(e) {
			this.designerSwiperIndex = e.detail.current
		},
		handleDesignerTabClick(index) {
			this.activeDesignerTab = index
			this.designerSwiperIndex = 0 // 切换 tab 时重置 swiper 索引
		},
		handleBrandTabClick(tab) {
			// 切换品牌馆标签
			this.activeBrandTab = tab
		},
		handleBrandClick(brand) {
			// 跳转到品牌详情页面，传递品牌ID等信息
			uni.navigateTo({
				url: `/pages/brand/detail?id=${brand.id || 1}&name=${encodeURIComponent(brand.name || '')}`
			})
		},
		handleBottomAction(action, index) {
			// 处理底部按钮点击
			if (action.title === '优惠券') {
				uni.navigateTo({
					url: '/pages/coupon/index'
				})
			} else if (action.title === '预约单') {
				// 可以添加预约单页面跳转
				console.log('跳转到预约单页面')
			} else if (action.title === '会员') {
				// 可以添加会员页面跳转
				console.log('跳转到会员页面')
			} else if (action.title === '入驻中') {
				// 可以添加入驻页面跳转
				console.log('跳转入驻页面')
			}
		}
	},
}
</script>

<style scoped lang="scss">
.profile-section {
	width: 100%;
	max-width: 750rpx;
	margin: 0 auto;
	padding: 0 12rpx;
	display: flex;
	flex-direction: column;
	gap: 16rpx;
	box-sizing: border-box;
}

/* 提示卡片 */
.alert-card {
	width: 100%;
	background-color: #303136;
	border-radius: 12rpx;
	padding:16rpx 20rpx;
	box-sizing: border-box;
}

.alert-content {
	display: flex;
	align-items: center;
	justify-content: space-between;
}

.alert-left {
	display: flex;
	align-items: center;
	gap: 16rpx;
}

.avatar {
	width: 60rpx;
	height: 60rpx;
	border-radius: 50%;
	overflow: hidden;
	flex-shrink: 0;
}

.avatar-img {
	width: 100%;
	height: 100%;
}

.alert-text {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 22rpx;
	color: #dacbb1;
	font-weight: 500;
	white-space: nowrap;
	overflow: hidden;
	text-overflow: ellipsis;
}

.close-btn {
	width: 56rpx;
	height: 56rpx;
	display: flex;
	align-items: center;
	justify-content: center;
	flex-shrink: 0;
}

.close-icon {
	width: 56rpx;
	height: 56rpx;
}

/* 快捷操作卡片 */
.quick-actions-card {
	width: 100%;
	background-color: #ffffff;
	border-radius: 12rpx;
	overflow: hidden;
}

.quick-actions-top {
	display: flex;
	align-items: center;
	gap: 12rpx;
}

.quick-action-item {
	flex: 1;
	height: 240rpx;
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	gap: 14rpx;
	padding: 30rpx 32rpx;
}

.action-icon {
	width: 88rpx;
	height: 88rpx;
}

.action-info {
	display: flex;
	flex-direction: column;
	align-items: center;
	gap: 4rpx;
}

.action-title {
	font-family: 'DIN_Black-Regular', Helvetica;
	font-size: 26rpx;
	color: #000000;
}

.action-subtitle {
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-size: 20rpx;
	color: #a6a6a6;
	text-align: center;
}

.quick-actions-bottom {
	display: flex;
	align-items: center;
	justify-content: space-between;
	padding: 0 30rpx 20rpx;
}

.bottom-action-item {
	display: flex;
	flex-direction: column;
	align-items: center;
	gap: 6rpx;
}

.action-title-small {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 24rpx;
	color: #000000;
	text-align: center;
	font-weight: 500;
}

.action-subtitle-small {
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-size: 18rpx;
	color: #a6a6a6;
	text-align: center;
}

/* 卡片通用样式 */
.portfolio-card,
.designers-card,
.brands-card {
	width: 100%;
	background-color: #ffffff;
	border-radius: 12rpx;
	padding: 20rpx;
	display: flex;
	flex-direction: column;
	gap: 14rpx;
	box-sizing: border-box;
}

.card-header {
	display: flex;
	align-items: flex-end;
	justify-content: space-between;
}

.card-title {
	font-family: 'DIN_Black-Regular', Helvetica;
	font-size: 28rpx;
	color: #000000;
}

.more-icon {
	width: 44rpx;
	height: 44rpx;
}

/* 作品集 */
.portfolio-content {
	width: 100%;
	height: 216rpx;
	position: relative;
}

.portfolio-item {
	position: absolute;
	top: 0;
	width: 372rpx;
	height: 216rpx;
}

.portfolio-img {
	position: absolute;
	top: 0;
	left: 0;
	width: 370rpx;
	height: 216rpx;
	border-radius: 8rpx;
}

.portfolio-overlay {
	position: absolute;
	top: 0;
	left: 2rpx;
	width: 372rpx;
	height: 216rpx;
}

.portfolio-gradient {
	position: absolute;
	bottom: 0;
	height: 48rpx;
}

.portfolio-label {
	position: absolute;
	bottom: 0;
	height: 48rpx;
	display: flex;
	align-items: center;
	gap: 8rpx;
}

.label-text {
	font-family: 'PingFang_SC-Semibold', Helvetica;
	font-size: 24rpx;
	color: #ffffff;
}

.label-count {
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-size: 24rpx;
	color: rgba(255, 255, 255, 0.6);
}

/* Tabs */
.tabs-scroll {
	width: 100%;
	white-space: nowrap;
}

.tabs-container {
	display: flex;
	align-items: center;
	gap: 30rpx;
}

.tab-item {
	height: auto;
	padding: 0;
	font-size: 26rpx;
	color: #a6a6a6;
	font-family: 'PingFang_SC-Regular', Helvetica;
}

.tab-item.active {
	color: #333333;
	font-family: 'PingFang_SC-Semibold', Helvetica;
	font-weight: 600;
}

/* 设计师 */
.designers-swiper {
	width: 100%;
	height: 480rpx;
}

.designers-swiper-item {
	height: 100%;
	display: flex;
	flex-direction: column;
}

.designers-container {
	display: flex;
	align-items: flex-start;
	justify-content: space-between;
	gap: 20rpx;
	padding: 0 12rpx;
	box-sizing: border-box;
	height: 100%;
}

.designer-card {
	flex: 1;
	min-width: 0;
	max-width: calc(50% - 10rpx);
	border: 2rpx solid #f3f3f3;
	border-radius: 8rpx;
	overflow: hidden;
	box-sizing: border-box;
}

.designer-img-wrapper {
	position: relative;
	width: 100%;
	height: 318rpx;
}

.designer-img-bg {
	position: absolute;
	top: 0;
	left: 0;
	width: 316rpx;
	height: 316rpx;
	border-radius: 8rpx 8rpx 0 0;
	background: linear-gradient(180deg, rgba(244, 244, 244, 1) 0%);
}

.designer-img {
	position: absolute;
	top: 2rpx;
	left: 0;
	width: 316rpx;
	height: 316rpx;
}

.designer-info {
	display: flex;
	flex-direction: column;
	gap: 6rpx;
	padding: 22rpx 22rpx 16rpx;
}

.designer-header {
	display: flex;
	align-items: center;
	gap: 8rpx;
	width: 100%;
}

.designer-name {
	font-family: 'PingFang_SC-Semibold', Helvetica;
	font-size: 30rpx;
	color: #000000;
}

.designer-badge {
	padding: 4rpx 8rpx;
	border-radius: 4rpx;
	font-size: 20rpx;
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-weight: 500;
}

.designer-badge.secondary {
	background-color: #f6f6f6;
	color: #666666;
}

.designer-badge.primary {
	background-color: #dacbb1;
	color: #645e57;
}

.designer-title {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 22rpx;
	color: #a6a6a6;
	font-weight: 500;
}

.designer-footer {
	display: flex;
	align-items: flex-start;
	justify-content: space-between;
	width: 100%;
}

.rating-info {
	display: flex;
	align-items: center;
	gap: 6rpx;
}

.rating-score {
	font-family: 'PingFang_SC-Semibold', Helvetica;
	font-size: 24rpx;
	color: #333333;
}

.star {
	font-size: 20rpx;
	color: #333333;
}

.review-count {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 24rpx;
	color: #333333;
	font-weight: 500;
}

.distance {
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-size: 24rpx;
	color: #333333;
}

.pagination-dots {
	display: flex;
	align-items: center;
	gap: 6rpx;
	justify-content: center;

}

.dot {
	height: 10rpx;
	border-radius: 5rpx;
	background-color: #d9d9d9;
}

.dot.active {
	background-color: #333333;
	border-radius: 28rpx;
}

/* 品牌馆 */
.brands-scroll {
	width: 100%;
	white-space: nowrap;
	box-sizing: border-box;
	/* 确保回弹效果正常 */
	-webkit-overflow-scrolling: touch;
}

.brands-container {
	display: flex;
	align-items: center;
	gap: 20rpx;
}

.brand-card {
	flex: 0 0 420rpx;
	width: 420rpx;
	border: 2rpx solid #f3f3f3;
	border-radius: 8rpx;
	overflow: hidden;
	position: relative;
}

.brand-img-wrapper {
	position: relative;
	width: 100%;
	height: 236rpx;
}

.brand-img-bg {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 236rpx;
	border-radius: 8rpx 8rpx 0 0;
	background: linear-gradient(180deg, rgba(244, 244, 244, 1) 0%);
}

.brand-img {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 236rpx;
}

.brand-info {
	display: flex;
	flex-direction: column;
	gap: 6rpx;
	padding: 22rpx 22rpx 16rpx;
}

.brand-name {
	font-family: 'PingFang_SC-Semibold', Helvetica;
	font-size: 30rpx;
	color: #000000;
}

.brand-rating {
	display: flex;
	align-items: center;
	gap: 6rpx;
}

.stars {
	display: flex;
	align-items: center;
	gap: 4rpx;
}

.brand-address {
	display: flex;
	align-items: center;
	gap: 6rpx;
	justify-content: flex-start;
	width: 100%;
}

.location-icon {
	width: 28rpx;
	height: 28rpx;
	flex-shrink: 0;
}

.address-text {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 22rpx;
	color: #666666;
	font-weight: 500;
	flex: 1;
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
}

.brand-address .distance {
	margin-left: 8rpx;
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-size: 22rpx;
	color: #a6a6a6;
	white-space: nowrap;
}

.brand-overlay {
	position: absolute;
	top: 0;
	left: 202rpx;
	width: 54rpx;
	height: 402rpx;
	background: linear-gradient(270deg, rgba(255, 255, 255, 1) 0%, rgba(255, 255, 255, 1) 61%, rgba(255, 255, 255, 0) 100%);
}

/* 优服务 */
.services-section {
	width: 100%;
	padding: 0 8rpx;
	display: flex;
	flex-direction: column;
	gap: 10rpx;
	box-sizing: border-box;
}

.services-header {
	display: flex;
	align-items: flex-end;
	justify-content: space-between;
	width: 100%;
}

.services-title {
	font-family: 'DIN_Black-Regular', Helvetica;
	font-size: 32rpx;
	color: #000000;
}

.filter-btn {
	display: flex;
	align-items: center;
	gap: 4rpx;
	height: auto;
	padding: 0;
}

.filter-text {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 28rpx;
	color: #666666;
	text-align: center;
	font-weight: 500;
}

.filter-icon {
	width: 20rpx;
	height: 20rpx;
}

.service-tabs-scroll {
	width: 100%;
	white-space: nowrap;
}

.service-tabs-container {
	display: flex;
	align-items: flex-start;
	justify-content: flex-start;
	gap: 36rpx;
	width: auto;
	min-width: 100%;
	flex-wrap: nowrap;
	// padding: 0 11rpx;
}

.service-tab-item {
	display: flex;
	flex-direction: column;
	align-items: center;
	gap: 12rpx;
	position: relative;
	height: auto;
	padding: 0;
	font-size: 28rpx;
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-weight: 400;
	color: #a6a6a6;
	white-space: nowrap;
	flex-shrink: 0;
}

.service-tab-item text {
	white-space: nowrap;
}

.service-tab-item.active {
	color: #000000;
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-weight: 400;
}

.tab-indicator {
	width: 20rpx;
	height: 6rpx;
}

.services-grid {
	display: flex;
	flex-wrap: wrap;
	align-items: center;
	justify-content: space-between;
	gap: 10rpx;
	width: 100%;
}

.service-card {
	width: calc((100% - 10rpx) / 2);
	border-radius: 12rpx;
	background-color: #ffffff;
	overflow: hidden;
	box-sizing: border-box;
}

.service-img {
	width: 100%;
	height: 358rpx;
	border-radius: 12rpx 12rpx 0 0;
}

.service-info {
	display: flex;
	flex-direction: column;
	gap: 12rpx;
	padding: 16rpx 16rpx;
}

.service-title {
	font-family: 'PingFang_SC-Semibold', Helvetica;
	font-size: 32rpx;
	color: #000000;
}

.service-desc {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 24rpx;
	color: #a6a6a6;
	font-weight: 500;
}

.service-price {
	display: flex;
	align-items: center;
	gap: 6rpx;
}

.price-symbol {
	font-family: 'PingFang_SC-Semibold', Helvetica;
	font-size: 28rpx;
	color: #333333;
}

.price-value {
	font-family: 'FZChaoCuHei-M10T-Regular', Helvetica;
	font-size: 28rpx;
	color: #333333;
	white-space: nowrap;
}

.service-footer {
	display: flex;
	align-items: flex-end;
	justify-content: space-between;
	width: 100%;
}

.service-designer {
	display: flex;
	align-items: center;
	gap: 12rpx;
}

.service-avatar {
	width: 52rpx;
	height: 52rpx;
	border-radius: 50%;
	overflow: hidden;
}

.avatar-img-small {
	width: 100%;
	height: 100%;
}

.designer-details {
	display: flex;
	flex-direction: column;
	gap: 4rpx;
}

.designer-name-small {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 22rpx;
	color: #333333;
	font-weight: 500;
}

.designer-role-small {
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-size: 22rpx;
	color: #a6a6a6;
}

.designer-rating {
	display: flex;
	align-items: center;
	gap: 4rpx;
}

.rating-score-small {
	font-family: 'PingFang_SC-Semibold', Helvetica;
	font-size: 24rpx;
	color: #333333;
}

.star-small {
	font-size: 20rpx;
	color: #333333;
}

.review-count-small {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-size: 24rpx;
	color: #333333;
	font-weight: 500;
}

.service-distance {
	font-family: 'PingFang_SC-Regular', Helvetica;
	font-size: 22rpx;
	color: #a6a6a6;
}

/* 动画 */
@keyframes fade-in {
	0% {
		opacity: 0;
		transform: translateY(-20rpx);
	}
	to {
		opacity: 1;
		transform: none;
	}
}

.animate-fade-in {
	animation: fade-in 1s ease forwards;
	opacity: 0;
}
</style>

// 源/waw_style_copy_-__4w0mnt/src/screens/Screen/sections/ProfileSection/ProfileSection.tsx
import React from "react";
import { Card, CardContent } from "../../../../components/ui/card";
import { Badge } from "../../../../components/ui/badge";
import { Button } from "../../../../components/ui/button";
import { Tabs, TabsList, TabsTrigger } from "../../../../components/ui/tabs";
import { ChevronRightIcon, XIcon, MapPinIcon, StarIcon } from "lucide-react";
import { Avatar, AvatarImage, AvatarFallback } from "../../../../components/ui/avatar";

const quickActions = [
  {
    icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2284.svg",
    title: "设计师",
    subtitle: "发现宝藏设计师",
  },
  {
    icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2280.svg",
    title: "优服务",
    subtitle: "甄选特色服务",
  },
  {
    icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2278.svg",
    title: "品牌馆",
    subtitle: "优质线下门店",
  },
];

const bottomActions = [
  {
    icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2005.svg",
    title: "预约单",
    subtitle: "你的预约订单",
  },
  {
    icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2006.svg",
    title: "优惠券",
    subtitle: "更多折扣等你",
  },
  {
    icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2007.svg",
    title: "会员",
    subtitle: "VIP平台特权",
  },
  {
    icon: "https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-2008.svg",
    title: "入驻中",
    subtitle: "诚邀全球设计师",
  },
];

const portfolioItems = [
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-175.png",
    overlay: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-177-1.svg",
    gradient: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-179.svg",
    label: "WOMAN",
    count: "12,349+",
    align: "left",
  },
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-176.png",
    overlay: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-178.svg",
    gradient: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-180.svg",
    label: "MAN",
    count: "12,349+",
    align: "right",
  },
];

const designerTabs = ["首席创意", "总监店长", "网红名师", "国际导师"];

const designers = [
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-153-1.png",
    name: "李天天",
    role: "美发师",
    level: "高级",
    title: "总监｜从业十年",
    rating: "4.8",
    reviews: "234",
    distance: "6.7km",
  },
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-153-1.png",
    name: "李天天",
    role: "美发师",
    level: "高级",
    title: "总监｜从业十年",
    rating: "4.8",
    reviews: "234",
    distance: "6.7km",
  },
];

const brandTabs = ["专业店", "品牌店", "工作室", "综合店"];

const brands = [
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-153-2.png",
    name: "成都意念美发造型沙龙",
    rating: "4.8",
    reviews: "768",
    address: "成都青羊区草堂路12号...",
    distance: "7.5km",
    width: "w-[210px]",
  },
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-153-3.png",
    name: "成都意念美发造",
    rating: "4.8",
    reviews: "768",
    address: "成都青羊区草堂路",
    distance: "",
    width: "w-[120px]",
    hasOverlay: true,
  },
];

const serviceTabs = ["全部", "洗吹", "剪发", "烫发", "染发", "护发", "头皮", "接发"];

const services = [
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-169-3.png",
    title: "烫发",
    description: "发型提案+染发+造型",
    price: "799",
    designerName: "李天天",
    designerRole: "美发师",
    rating: "4.8",
    reviews: "768",
    distance: "6.7km",
    avatar: "https://c.animaapp.com/mi4v97d2OSuz2g/img/ellipse-34.svg",
  },
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-169-3.png",
    title: "烫发",
    description: "发型提案+染发+造型",
    price: "799",
    designerName: "李天天",
    designerRole: "美发师",
    rating: "4.8",
    reviews: "768",
    distance: "6.7km",
    avatar: "https://c.animaapp.com/mi4v97d2OSuz2g/img/ellipse-34.svg",
  },
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-169-3.png",
    title: "烫发",
    description: "发型提案+染发+造型",
    price: "799",
    designerName: "李天天",
    designerRole: "美发师",
    rating: "4.8",
    reviews: "768",
    distance: "6.7km",
    avatar: "https://c.animaapp.com/mi4v97d2OSuz2g/img/ellipse-34.svg",
  },
  {
    image: "https://c.animaapp.com/mi4v97d2OSuz2g/img/rectangle-169-3.png",
    title: "烫发",
    description: "发型提案+染发+造型",
    price: "799",
    designerName: "李天天",
    designerRole: "美发师",
    rating: "4.8",
    reviews: "768",
    distance: "6.7km",
    avatar: "https://c.animaapp.com/mi4v97d2OSuz2g/img/ellipse-34.svg",
  },
];

const paginationDots = [
  { active: false, width: "w-[5px]" },
  { active: false, width: "w-[5px]" },
  { active: true, width: "w-3.5" },
  { active: false, width: "w-[5px]" },
];

export const ProfileSection = (): JSX.Element => {
  return (
    <section className="flex flex-col w-full items-start gap-2 px-1.5">
<Card className="w-full bg-[#303136] border-0 rounded translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:0ms]">
<CardContent className="flex items-center justify-between p-2.5">
<div className="inline-flex items-center gap-2">
<Avatar className="w-[30px] h-[30px]">
<AvatarImage src="https://c.animaapp.com/mi4v97d2OSuz2g/img/ellipse-71.svg" />
<AvatarFallback>U</AvatarFallback>
</Avatar>
<p className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#dacbb1] text-[11px]">
hey,快去看看你周边设计师吧！
            </p>
</div>
<Button variant="ghost" size="icon" className="h-7 w-7 p-0">
<img
              className="w-7 h-7"
              alt="Close"
              src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-6.svg"
            />
</Button>
</CardContent>
</Card>
<Card className="w-full border-0 rounded-md translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:100ms]">
<CardContent className="p-0">
<div className="flex items-center gap-1.5">
{quickActions.map((action, index) => (
              <Button
                key={index}
                variant="ghost"
                className="flex-1 h-[120px] flex-col gap-[7px] px-4 py-[15px] hover:bg-accent/50 transition-colors"
              >
<img className="w-11 h-11" alt={action.title} src={action.icon} />
<div className="flex flex-col items-center gap-0.5">
<span className="[font-family:'DIN_Black-Regular',Helvetica] font-normal text-black text-[13px]">
{action.title}
                  </span>
<span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#a6a6a6] text-[10px] text-center">
{action.subtitle}
                  </span>
</div>
</Button>
))}
          </div>
<div className="flex items-center justify-between px-[15px] py-2.5 border-t">
{bottomActions.map((action, index) => (
              <Button
                key={index}
                variant="ghost"
                className="flex-col h-auto gap-[3px] p-0 hover:bg-accent/50 transition-colors"
              >
<img className="w-11 h-11" alt={action.title} src={action.icon} />
<div className="flex flex-col items-center">
<span className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-black text-xs text-center">
{action.title}
                  </span>
<span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#a6a6a6] text-[9px] text-center">
{action.subtitle}
                  </span>
</div>
</Button>
))}
          </div>
</CardContent>
</Card>
<Card className="w-full border-0 rounded-md translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:200ms]">
<CardContent className="p-2.5 flex flex-col gap-[7px]">
<div className="flex items-end justify-between">
<h2 className="[font-family:'DIN_Black-Regular',Helvetica] font-normal text-black text-sm">
作品集
            </h2>
<Button variant="ghost" size="icon" className="h-[22px] w-[22px] p-0">
<img
                className="w-[22px] h-[22px]"
                alt="More"
                src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-7.svg"
              />
</Button>
</div>
<div className="relative w-full h-[108px]">
{portfolioItems.map((item, index) => (
              <div
                key={index}
                className={`absolute top-0 ${index === 0 ? "left-0" : "left-[157px]"} w-[186px] h-[108px]`}
              >
<img
                  className={`absolute top-0 ${index === 0 ? "left-0" : "left-px"} w-[185px] h-[108px]`}
                  alt={item.label}
                  src={item.image}
                />
<img
                  className={`absolute top-0 ${index === 0 ? "left-0" : "left-px"} w-[186px] h-[108px]`}
                  alt="Overlay"
                  src={item.overlay}
                />
<img
                  className={`absolute top-[84px] ${index === 0 ? "left-0" : "left-[29px]"} ${index === 0 ? "w-[186px]" : "w-[157px]"} h-6`}
                  alt="Gradient"
                  src={item.gradient}
                />
<div
                  className={`flex items-center gap-1 absolute top-[87px] ${item.align === "left" ? "left-2.5" : "left-[100px]"}`}
                >
{item.align === "left" ? (
                    <>
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-white text-xs">
{item.label}
                      </span>
<span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#ffffff99] text-xs">
{item.count}
                      </span>
</>
) : (
                    <>
<span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#ffffff99] text-xs">
{item.count}
                      </span>
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-white text-xs">
{item.label}
                      </span>
</>
)}
                </div>
</div>
))}
          </div>
</CardContent>
</Card>
<Card className="w-full border-0 rounded-md translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:300ms]">
<CardContent className="p-2.5 flex flex-col gap-2">
<div className="flex items-end justify-between">
<h2 className="[font-family:'DIN_Black-Regular',Helvetica] font-normal text-black text-sm">
设计师
            </h2>
<Button variant="ghost" size="icon" className="h-[22px] w-[22px] p-0">
<img
                className="w-[22px] h-[22px]"
                alt="More"
                src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-7.svg"
              />
</Button>
</div>
<div className="flex items-center gap-[15px] overflow-x-auto">
{designerTabs.map((tab, index) => (
              <Button
                key={index}
                variant="ghost"
                className={`h-auto p-0 ${index === 0 ? "[font-family:'PingFang_SC-Semibold',Helvetica] text-[#333333]" : "[font-family:'PingFang_SC-Regular',Helvetica] text-[#a6a6a6]"} font-normal text-[13px] hover:text-[#333333] transition-colors`}
              >
{tab}
              </Button>
))}
          </div>
<div className="flex items-center gap-2.5">
{designers.map((designer, index) => (
              <Card key={index} className="w-[158px] border border-[#f3f3f3] rounded">
<CardContent className="p-0 pb-2">
<div className="flex flex-col items-center gap-1.5">
<div className="relative w-[158px] h-[159px]">
<div className="absolute top-0 left-0 w-[158px] h-[158px] rounded-[4px_4px_0px_0px] bg-[linear-gradient(180deg,rgba(244,244,244,1)_0%)]" />
<img
                        className="absolute top-px left-0 w-[158px] h-[158px]"
                        alt={designer.name}
                        src={designer.image}
                      />
</div>
<div className="flex flex-col items-start gap-[3px] px-[11px] py-1 w-full">
<div className="flex items-center gap-1 w-full">
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-black text-[15px]">
{designer.name}
                        </span>
<Badge
                          variant="secondary"
                          className="bg-[#f6f6f6] text-[#666666] text-[10px] px-1 py-px h-auto [font-family:'PingFang_SC-Medium',Helvetica] font-medium"
                        >
{designer.role}
                        </Badge>
<Badge
                          variant="secondary"
                          className="bg-[#dacbb1] text-[#645e57] text-[10px] px-1 py-px h-auto [font-family:'PingFang_SC-Medium',Helvetica] font-medium"
                        >
{designer.level}
                        </Badge>
</div>
<p className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#a6a6a6] text-[11px]">
{designer.title}
                      </p>
<div className="flex items-start justify-between w-full">
<div className="inline-flex items-center gap-[3px]">
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-[#333333] text-xs">
{designer.rating}
                          </span>
<StarIcon className="w-2.5 h-2.5 fill-current text-[#333333]" />
<span className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#333333] text-xs">
({designer.reviews})
                          </span>
</div>
<span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#333333] text-xs">
{designer.distance}
                        </span>
</div>
</div>
</div>
</CardContent>
</Card>
))}
          </div>
<div className="inline-flex items-center gap-[3px] justify-center">
{paginationDots.map((dot, index) => (
              <div
                key={index}
                className={`${dot.width} h-[5px] ${dot.active ? "bg-[#333333] rounded-[14px]" : "bg-[#d9d9d9] rounded-[2.5px]"}`}
              />
))}
          </div>
</CardContent>
</Card>
<Card className="w-full border-0 rounded-md translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:400ms]">
<CardContent className="p-2.5 flex flex-col gap-2">
<div className="flex items-end justify-between">
<h2 className="[font-family:'DIN_Black-Regular',Helvetica] font-normal text-black text-sm">
品牌馆
            </h2>
<Button variant="ghost" size="icon" className="h-[22px] w-[22px] p-0">
<img
                className="w-[22px] h-[22px]"
                alt="More"
                src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-7.svg"
              />
</Button>
</div>
<div className="flex items-center gap-[15px] overflow-x-auto">
{brandTabs.map((tab, index) => (
              <Button
                key={index}
                variant="ghost"
                className={`h-auto p-0 ${index === 0 ? "[font-family:'PingFang_SC-Semibold',Helvetica] text-[#333333]" : "[font-family:'PingFang_SC-Regular',Helvetica] text-[#a6a6a6]"} font-normal text-[13px] hover:text-[#333333] transition-colors`}
              >
{tab}
              </Button>
))}
          </div>
<div className="flex items-center gap-2.5">
{brands.map((brand, index) => (
              <Card
                key={index}
                className={`${brand.width} border border-[#f3f3f3] rounded relative`}
              >
<CardContent className="p-0 pb-2">
<div className="flex flex-col items-center gap-1.5">
<div className={`${brand.width} h-[118px] relative`}>
{!brand.hasOverlay && (
                        <div className="absolute top-0 left-0 w-40 h-[118px] rounded-[4px_4px_0px_0px] bg-[linear-gradient(180deg,rgba(244,244,244,1)_0%)]" />
)}
                      <img
                        className={`${brand.hasOverlay ? "absolute top-0 left-0" : "absolute top-0 left-0"} ${brand.width} h-[118px] ${brand.hasOverlay ? "bg-[100%_100%]" : ""}`}
                        alt={brand.name}
                        src={brand.image}
                      />
</div>
<div className="flex flex-col items-start gap-[3px] px-[11px] py-1 w-full">
<div className="flex items-center gap-1 w-full">
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-black text-[15px]">
{brand.name}
                        </span>
</div>
<div className="inline-flex items-center gap-[3px]">
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-[#333333] text-xs">
{brand.rating}
                        </span>
<div className="inline-flex items-center gap-0.5">
{brand.hasOverlay ? (
                            <>
<StarIcon className="w-2.5 h-2.5 fill-current text-[#333333]" />
<StarIcon className="w-2.5 h-2.5 fill-current text-[#333333]" />
<StarIcon className="w-2.5 h-2.5 fill-current text-[#333333]" />
</>
) : (
                            <StarIcon className="w-2.5 h-2.5 fill-current text-[#333333]" />
)}
                        </div>
<span className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#333333] text-xs">
({brand.reviews})
                        </span>
</div>
<div className={`flex items-center ${brand.distance ? "justify-between w-full" : "gap-0.5"}`}>
<div className="inline-flex items-center gap-0.5">
<MapPinIcon className="w-3.5 h-3.5 text-[#666666]" />
<span className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#666666] text-[11px]">
{brand.address}
                          </span>
</div>
{brand.distance && (
                          <span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#666666] text-[11px]">
{brand.distance}
                          </span>
)}
                      </div>
</div>
{brand.hasOverlay && (
                      <div className="absolute top-0 left-[101px] w-[27px] h-[201px] bg-[linear-gradient(270deg,rgba(255,255,255,1)_0%,rgba(255,255,255,1)_61%,rgba(255,255,255,0)_100%)]" />
)}
                  </div>
</CardContent>
</Card>
))}
          </div>
</CardContent>
</Card>
<div className="flex flex-col items-center gap-[5px] w-full translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:500ms]">
<div className="flex flex-col items-start gap-2.5 px-0.5 py-0 w-full">
<div className="flex items-end justify-between w-full">
<h2 className="[font-family:'DIN_Black-Regular',Helvetica] font-normal text-black text-base">
优服务
            </h2>
<Button variant="ghost" className="h-auto p-0 gap-0.5">
<span className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#666666] text-sm text-center">
筛选
              </span>
<img
                className="w-2.5 h-2.5"
                alt="Filter"
                src="https://c.animaapp.com/mi4v97d2OSuz2g/img/frame-5.svg"
              />
</Button>
</div>
<div className="flex items-start justify-center gap-5 w-full overflow-x-auto">
{serviceTabs.map((tab, index) => (
              <div key={index} className="inline-flex flex-col items-center gap-2.5 relative">
<Button
                  variant="ghost"
                  className={`h-auto p-0 ${index === 0 ? "[font-family:'PingFang_SC-Semibold',Helvetica] text-black" : "[font-family:'PingFang_SC-Medium',Helvetica] text-[#a6a6a6]"} font-normal text-sm text-center hover:text-black transition-colors`}
                >
{tab}
                </Button>
{index === 0 && (
                  <img
                    className="w-2.5 h-[3px]"
                    alt="Active indicator"
                    src="https://c.animaapp.com/mi4v97d2OSuz2g/img/vector-15.svg"
                  />
)}
              </div>
))}
          </div>
</div>
<div className="flex flex-wrap items-center justify-between gap-[5px] w-full">
{services.map((service, index) => (
            <Card key={index} className="w-[179px] border-0 rounded bg-white">
<CardContent className="p-0 pb-2">
<div className="flex flex-col items-center gap-[7px]">
<img
                    className="w-full h-[179px] rounded object-cover"
                    alt={service.title}
                    src={service.image}
                  />
<div className="flex flex-col items-start gap-1.5 px-2 py-0 w-full">
<div className="flex flex-col items-start gap-[3px] w-full">
<div className="flex items-center gap-[3px] w-full">
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-black text-base">
{service.title}
                        </span>
</div>
<div className="flex flex-col items-start gap-[3px] w-full">
                        <p className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#a6a6a6] text-xs">
                          {service.description}
                        </p>
<div className="inline-flex items-center gap-[3px]">
<div className="inline-flex items-center">
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-[#333333] text-sm">
¥
                            </span>
<span className="[font-family:'FZChaoCuHei-M10T-Regular',Helvetica] font-normal text-[#333333] text-sm whitespace-nowrap">
{service.price}
                            </span>
</div>
</div>
</div>
</div>
<div className="flex items-end justify-between w-full">
<div className="inline-flex items-center gap-1.5">
<Avatar className="w-[26px] h-[26px]">
<AvatarImage src={service.avatar} />
<AvatarFallback className="bg-[#a6a6a6]">D</AvatarFallback>
</Avatar>
<div className="inline-flex flex-col items-start gap-0.5">
<div className="inline-flex items-start gap-1">
<span className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#333333] text-[11px]">
{service.designerName}
                            </span>
<span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#a6a6a6] text-[11px]">
{service.designerRole}
                            </span>
</div>
<div className="inline-flex items-center gap-0.5">
<span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-[#333333] text-xs">
{service.rating}
                            </span>
<StarIcon className="w-2.5 h-2.5 fill-current text-[#333333]" />
<span className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#333333] text-xs">
({service.reviews})
                            </span>
</div>
</div>
</div>
<span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#a6a6a6] text-[11px]">
{service.distance}
                      </span>
</div>
</div>
</div>
</CardContent>
</Card>
))}
        </div>
</div>
</section>
);
};
