// 源/私人领地页面/src/screens/DivWrapperScreen/DivWrapperScreen.tsx
import { MoreVerticalIcon, RadioIcon } from "lucide-react";
import React from "react";
import { Button } from "../../components/ui/button";
import { BookingSection } from "./sections/BookingSection";
import { HeaderSection } from "./sections/HeaderSection";
import { ServiceCardSection } from "./sections/ServiceCardSection";
import { ServiceListSection } from "./sections/ServiceListSection";
import { UserProfileSection } from "./sections/UserProfileSection";

export const DivWrapperScreen = (): JSX.Element => {
  return (
    <div
      className="bg-[#f2f2f2] overflow-hidden w-full min-w-[375px] flex flex-col relative"
      data-model-id="15:5244"
    >
      <header className="w-full bg-white flex flex-col relative z-10">
        <div className="w-full h-11 flex items-center justify-between px-4 translate-y-[-1rem] animate-fade-in opacity-0">
          <div className="flex items-center gap-2">
            <span className="[font-family:'Inter',Helvetica] font-normal text-black text-sm tracking-[0] leading-[normal]">
              9:41
            </span>
          </div>
          <div className="flex items-center gap-1">
            <img
              className="w-[17.42px] h-[10.67px]"
              alt="Cellular connection"
              src="https://c.animaapp.com/mi5ng54v4eM3X6/img/cellular-connection.svg"
            />
            <img
              className="w-[15.64px] h-[11px]"
              alt="Wifi"
              src="https://c.animaapp.com/mi5ng54v4eM3X6/img/wifi.svg"
            />
            <img
              className="w-[24.42px] h-[11.33px]"
              alt="Battery"
              src="https://c.animaapp.com/mi5ng54v4eM3X6/img/battery.png"
            />
          </div>
        </div>

        <nav className="w-full h-[68px] flex items-center justify-between px-4 relative translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:200ms]">
          <Button variant="ghost" size="icon" className="h-auto w-auto p-0">
            <img
              className="w-4 h-4"
              alt="Back"
              src="https://c.animaapp.com/mi5ng54v4eM3X6/img/frame.svg"
            />
          </Button>

          <h1 className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#333333] text-base text-center tracking-[0] leading-[normal]">
            私人领地
          </h1>

          <div className="flex items-center gap-2">
            <Button variant="ghost" size="icon" className="h-auto w-auto p-0">
              <MoreVerticalIcon className="w-4 h-4 text-[#333333]" />
            </Button>
            <Button variant="ghost" size="icon" className="h-auto w-auto p-0">
              <RadioIcon className="w-4 h-4 text-[#333333]" />
            </Button>
          </div>

          <img
            className="absolute top-[-37px] right-0 w-32 h-[72px]"
            alt="Group"
            src="https://c.animaapp.com/mi5ng54v4eM3X6/img/group-8.png"
          />
        </nav>
      </header>

      <main className="flex-1 w-full flex flex-col items-center px-1.5 pt-1.5 gap-1.5 translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:400ms]">
        <HeaderSection />
        <UserProfileSection />
        <ServiceCardSection />
        <ServiceListSection />
        <BookingSection />
      </main>

      <footer className="w-full h-[34px] flex items-center justify-center px-[120px] py-2 translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:600ms]">
        <div className="w-[134px] h-[5px] bg-black rounded-[100px]" />
      </footer>
    </div>
  );
};

// 源/Payment Details to Be Paid/src/screens/DivWrapperScreen.vue
<template>
  <div class="div-wrapper-screen" data-model-id="53:5244">
    <div class="rectangle-2" />
    <div class="vector-wrapper">
      <img class="vector" alt="Vector" src="/img/vector.svg" />
    </div>
    <div class="element">
      <div class="iphone-x-status-bars-wrapper">
        <div class="iphone-x-status-bars">
          <div class="battery">
            <img class="border" alt="Border" src="/img/border.svg" />
            <img class="cap" alt="Cap" src="/img/cap.svg" />
            <img class="capacity" alt="Capacity" src="/img/capacity.svg" />
          </div>
          <img class="wifi" alt="Wifi" src="/img/wifi.svg" />
          <img class="cellular-connection" alt="Cellular connection" src="/img/cellular-connection.svg" />
          <div class="time-style">
            <div class="text-wrapper-16">9:41</div>
          </div>
        </div>
      </div>
    </div>
    <div class="group">
      <img class="img" alt="Vector" src="/img/vector-13.svg" />
      <div class="ellipse" />
      <div class="ellipse-2" />
      <div class="ellipse-3" />
      <div class="ellipse-4" />
      <div class="ellipse-5" />
    </div>
    <FrameSubsection />
    <FrameWrapperSubsection />
    <div class="frame-15">
      <div class="home-indicator-2" />
    </div>
    <div class="text-wrapper-17">订单详情</div>
    <DivWrapperSubsection />
  </div>
</template>

<script>
import FrameSubsection from "./DivWrapperScreen/sections/FrameSubsection.vue";
import FrameWrapperSubsection from "./DivWrapperScreen/sections/FrameWrapperSubsection.vue";
import DivWrapperSubsection from "./DivWrapperScreen/sections/DivWrapperSubsection.vue";

export default {
  name: "DivWrapperScreen",
  components: {
    FrameSubsection,
    FrameWrapperSubsection,
    DivWrapperSubsection,
  },
};
</script>

<style>
.div-wrapper-screen {
  background-color: #f2f2f2;
  min-height: 812px;
  min-width: 375px;
  overflow: hidden;
  position: relative;
  width: 100%;
}

.div-wrapper-screen .rectangle-2 {
  background-color: #ffffff;
  height: 156px;
  left: 0;
  position: absolute;
  top: 0;
  width: 375px;
}

.div-wrapper-screen .vector-wrapper {
  height: 16px;
  left: 15px;
  position: absolute;
  top: 58px;
  width: 16px;
}

.div-wrapper-screen .vector {
  height: 99.77%;
  left: 14.16%;
  position: absolute;
  top: 0;
  width: 56.08%;
}

.div-wrapper-screen .element {
  align-items: flex-start;
  display: flex;
  height: 44px;
  left: -14px;
  min-width: 384px;
  position: absolute;
  top: 1px;
}

.div-wrapper-screen .iphone-x-status-bars-wrapper {
  display: flex;
  height: 44px;
  width: 384px;
}

.div-wrapper-screen .iphone-x-status-bars {
  background-image: url(../../static/img/rectangle.svg);
  background-size: 100% 100%;
  flex: 1;
  position: relative;
  width: 384.17px;
}

.div-wrapper-screen .battery {
  height: 23.48%;
  left: 89.73%;
  position: absolute;
  top: 40.53%;
  width: 6.35%;
}

.div-wrapper-screen .border {
  height: 100%;
  left: -2.05%;
  position: absolute;
  top: -4.84%;
  width: 88.13%;
}

.div-wrapper-screen .cap {
  height: 38.71%;
  left: 94.43%;
  position: absolute;
  top: 30.64%;
  width: 5.57%;
}

.div-wrapper-screen .capacity {
  height: 70.97%;
  left: 6.30%;
  position: absolute;
  top: 14.52%;
  width: 75.54%;
}

.div-wrapper-screen .wifi {
  height: 24.92%;
  left: 84.18%;
  position: absolute;
  top: 39.39%;
  width: 4.07%;
}

.div-wrapper-screen .cellular-connection {
  height: 24.24%;
  left: 78.31%;
  position: absolute;
  top: 40.15%;
  width: 4.53%;
}

.div-wrapper-screen .time-style {
  display: flex;
  height: 38.64%;
  left: 9.11%;
  position: absolute;
  top: 35.23%;
  width: 7.99%;
}

.div-wrapper-screen .text-wrapper-16 {
  color: #000000;
  flex: 1;
  font-family: "Inter", Helvetica;
  font-size: 14px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  width: 28.69px;
}

.div-wrapper-screen .group {
  background-color: #ffffff80;
  border-radius: 17px;
  box-shadow: 0px 0px 22.1px #0000000f;
  height: 28px;
  left: 269px;
  position: absolute;
  top: 53px;
  width: 86px;
}

.div-wrapper-screen .img {
  height: 18px;
  left: 42px;
  position: absolute;
  top: 6px;
  width: 1px;
}

.div-wrapper-screen .ellipse {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 16px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.div-wrapper-screen .ellipse-2 {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 30px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.div-wrapper-screen .ellipse-3 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 22px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.div-wrapper-screen .ellipse-4 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 61px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.div-wrapper-screen .ellipse-5 {
  border: 1px solid;
  border-color: #000000;
  border-radius: 8px;
  height: 16px;
  left: 56px;
  position: absolute;
  top: 6px;
  width: 16px;
}

.div-wrapper-screen .frame-15 {
  align-items: center;
  bottom: 0;
  display: flex;
  flex-direction: column;
  gap: 10px;
  height: 34px;
  justify-content: flex-end;
  left: calc(50.00% - 188px);
  padding: 8px 120px;
  position: absolute;
  width: 375px;
}

.div-wrapper-screen .home-indicator-2 {
  background-color: #000000;
  border-radius: 100px;
  height: 5px;
  position: relative;
  width: 134px;
}

.div-wrapper-screen .text-wrapper-17 {
  color: #666666;
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 15px;
  font-weight: 500;
  left: 39px;
  letter-spacing: 0;
  line-height: normal;
  position: absolute;
  top: 56px;
}
</style>
