// components/coupon/index/CouponListSection.vue
<template>
	<view class="coupon-list-section">
		<view class="tab-list">
			<view 
				v-for="tab in tabItems" 
				:key="tab.id" 
				class="tab-item"
				:class="{ active: activeTab === tab.id }"
				@tap="handleTabClick(tab.id)"
			>
				<text class="tab-label" :class="{ active: activeTab === tab.id }">{{ tab.label }}</text>
				<image 
					v-if="activeTab === tab.id"
					class="tab-indicator" 
					src="https://c.animaapp.com/mi5m9weyYgJtGL/img/vector-15.svg" 
					mode="aspectFit"
				></image>
			</view>
		</view>
	</view>
</template>

<script>
export default {
	props: {
		activeTab: {
			type: String,
			default: 'service'
		}
	},
	data() {
		return {
			tabItems: [
				{ id: "service", label: "服务券" },
				{ id: "product", label: "商品券" },
				{ id: "ended", label: "已结束" },
			],
		}
	},
	methods: {
		handleTabClick(tabId) {
			this.$emit('tab-change', tabId)
		}
	}
}
</script>

<style scoped lang="scss">
.coupon-list-section {
	width: 100%;
	background-color: #ffffff;
	padding: 16rpx 32rpx 0;
	box-sizing: border-box;
	flex-shrink: 0;
}

.tab-list {
	display: flex;
	align-items: flex-start;
	justify-content: space-between;
	width: 100%;
}

.tab-item {
	display: inline-flex;
	flex-direction: column;
	align-items: center;
	gap: 8rpx;
	position: relative;
	padding-bottom: 16rpx;
	cursor: pointer;
	transition: color 0.3s;
}

.tab-label {
	position: relative;
	width: fit-content;
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-weight: 500;
	color: #a6a6a6;
	font-size: 28rpx;
	text-align: center;
	
	&.active {
		font-family: 'PingFang_SC-Semibold', Helvetica;
		font-weight: normal;
		color: #000000;
	}
}

.tab-indicator {
	position: absolute;
	bottom: 0;
	width: 20rpx;
	height: 6rpx;
	flex-shrink: 0;
}
</style>

// 源/coupon-end/src/screens/DivWrapper/sections/CouponListSection/CouponListSection.tsx
import React from "react";
import { Tabs, TabsList, TabsTrigger } from "../../../../components/ui/tabs";

const tabItems = [
  { value: "coupons", label: "优惠券" },
  { value: "product-vouchers", label: "商品券" },
  { value: "ended", label: "已结束" },
];

export const CouponListSection = (): JSX.Element => {
  return (
    <nav className="w-full px-4 py-6">
      <Tabs defaultValue="ended" className="w-full">
        <TabsList className="w-full h-auto bg-transparent p-0 grid grid-cols-3 gap-0">
          {tabItems.map((item, index) => (
            <TabsTrigger
              key={item.value}
              value={item.value}
              className={`
                h-auto py-0 px-0 
                [font-family:'PingFang_SC-Medium',Helvetica] 
                font-medium 
                text-sm 
                text-center 
                tracking-[0] 
                leading-normal
                data-[state=inactive]:text-[#a6a6a6]
                data-[state=active]:text-black
                data-[state=active]:[font-family:'PingFang_SC-Semibold',Helvetica]
                data-[state=active]:font-normal
                data-[state=inactive]:bg-transparent
                data-[state=active]:bg-transparent
                data-[state=inactive]:shadow-none
                data-[state=active]:shadow-none
                relative
                flex
                flex-col
                items-center
                gap-2.5
                transition-colors
              `}
            >
              <span className="mt-[-1px]">{item.label}</span>
              {item.value === "ended" && (
                <img
                  className="w-2.5 h-[3px] mb-[-0.5px]"
                  alt="Active indicator"
                  src="https://c.animaapp.com/mi5mjnswM14oP7/img/vector-15.svg"
                />
              )}
            </TabsTrigger>
          ))}
        </TabsList>
      </Tabs>
    </nav>
  );
};
