// 源/waw_style_copy_-__5bgw3v/src/screens/Screen/sections/VIPSection/VIPSection.tsx
import React from "react";
import { Button } from "../../../../components/ui/button";

export const VIPSection = (): JSX.Element => {
  return (
    <header className="flex w-full items-center justify-between">
      <h2 className="[font-family:'DIN_Black-Regular',Helvetica] font-normal text-black text-sm tracking-[0] leading-normal">
        附近推荐
      </h2>

      <Button
        variant="ghost"
        className="inline-flex items-center gap-0.5 h-auto p-0 hover:bg-transparent"
      >
        <span className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#666666] text-sm text-center tracking-[0] leading-normal">
          筛选
        </span>

        <img
          className="w-2.5 h-2.5"
          alt="Filter icon"
          src="https://c.animaapp.com/mi5bcgvrGbkedE/img/frame-1.svg"
        />
      </Button>
    </header>
  );
};

// components/main/index/VIPSection.vue
<template>
	<view class="vip-section">
		<text class="section-title">附近推荐</text>
		<view class="filter-btn" @tap="handleFilter">
			<text class="filter-text">筛选</text>
			<image class="filter-icon" src="https://c.animaapp.com/mi5bcgvrGbkedE/img/frame-1.svg" mode="aspectFit"></image>
		</view>
	</view>
</template>

<script>
export default {
	methods: {
		handleFilter() {
			console.log('Filter clicked')
		}
	}
}
</script>

<style scoped lang="scss">
.vip-section {
	display: flex;
	width: 100%;
	max-width: 100%;
	margin: 0 auto;
	padding: 0 12rpx;
	align-items: center;
	justify-content: space-between;
	box-sizing: border-box;
}

.section-title {
	font-family: 'DIN_Black-Regular', Helvetica;
	font-weight: normal;
	color: #000000;
	font-size: 28rpx;
}

.filter-btn {
	display: inline-flex;
	align-items: center;
	gap: 4rpx;
	height: auto;
	padding: 0;
}

.filter-text {
	font-family: 'PingFang_SC-Medium', Helvetica;
	font-weight: 500;
	color: #666666;
	font-size: 28rpx;
	text-align: center;
}

.filter-icon {
	width: 20rpx;
	height: 20rpx;
}


@keyframes fade-in {
	0% {
		opacity: 0;
		transform: translateY(-20rpx);
	}
	to {
		opacity: 1;
		transform: none;
	}
}

.animate-fade-in {
	animation: fade-in 1s ease forwards;
	opacity: 0;
}
</style>
