// 源/入住设计师-合作协议/src/screens/DivWrapper/DivWrapper.jsx
import { ChevronLeftIcon } from "lucide-react";
import React from "react";
import { Button } from "../../components/ui/button";
import { Card, CardContent } from "../../components/ui/card";
import { Checkbox } from "../../components/ui/checkbox";

export const DivWrapper = () => {
  const steps = [
    { label: "身份认证", active: false },
    { label: "职业认证", active: false },
    { label: "合作协议", active: true },
    { label: "结算信息", active: false },
  ];

  return (
    <div
      className="bg-[#f2f2f2] overflow-hidden w-full min-w-[375px] min-h-screen flex flex-col relative"
      data-model-id="145:9901"
    >
      <header className="w-full bg-white">
        <div className="flex items-center justify-between px-4 pt-11 pb-3">
          <button className="w-4 h-4 flex items-center justify-center">
            <ChevronLeftIcon className="w-4 h-4" />
          </button>

          <h1 className="[font-family:'PingFang_SC-Medium',Helvetica] font-medium text-[#666666] text-[15px] tracking-[0] leading-[normal]">
            设计师入驻
          </h1>

          <div className="flex items-center gap-2">
            <img
              className="w-32 h-[72px]"
              alt="Group"
              src="https://c.animaapp.com/miieqry098Kjoo/img/group-8.png"
            />
          </div>
        </div>

        <nav className="flex items-center justify-center gap-[38px] pb-3 relative">
          {steps.map((step, index) => (
            <button
              key={index}
              className={`[font-family:'PingFang_SC-${
                step.active ? "Semibold" : "Regular"
              }',Helvetica] font-normal text-[13px] tracking-[0] leading-[normal] ${
                step.active ? "text-black" : "text-[#a6a6a6]"
              }`}
            >
              {step.label}
            </button>
          ))}
        </nav>

        <div className="px-[41px] pb-2">
          <img
            className="w-full h-[23px]"
            alt="Progress"
            src="https://c.animaapp.com/miieqry098Kjoo/img/frame-2387.svg"
          />
        </div>
      </header>

      <main className="flex-1 px-1.5 pt-2 pb-[83px] translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:200ms]">
        <Card className="bg-white rounded-md border-0 shadow-none">
          <CardContent className="flex flex-col items-start gap-3 p-3">
            <div className="flex flex-col items-start gap-1">
              <h2 className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-black text-sm text-center tracking-[0] leading-[normal]">
                入驻平台协议
              </h2>
              <p className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#999999] text-xs text-center tracking-[0] leading-[normal]">
                请认真阅读本平台入驻协议
              </p>
            </div>

            <div className="w-full h-[447px] bg-[#f8f8f8] rounded" />

            <div className="flex items-end gap-[5px]">
              <Checkbox id="agreement" className="w-4 h-4" />
              <label
                htmlFor="agreement"
                className="[font-family:'Inter',Helvetica] font-medium text-xs tracking-[0] leading-[normal] cursor-pointer"
              >
                <span className="text-[#999999]">我已阅读并同意</span>
                <span className="text-[#6d58f1]">《**入驻申请说明》</span>
              </label>
            </div>
          </CardContent>
        </Card>
      </main>

      <footer className="w-full bg-white shadow-[0px_-1px_0px_#0000000a] fixed bottom-0 left-0">
        <div className="flex items-center justify-center gap-1.5 px-2.5 py-[3.5px]">
          <Button
            variant="outline"
            className="flex-1 h-[42px] rounded border border-solid border-[#e7e7e7] bg-white hover:bg-gray-50 transition-colors"
          >
            <span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-[#666666] text-xs tracking-[0] leading-[normal]">
              上一步
            </span>
          </Button>

          <Button className="flex-1 h-[42px] bg-[#333333] hover:bg-[#4d4d4d] rounded-sm transition-colors">
            <span className="[font-family:'PingFang_SC-Semibold',Helvetica] font-normal text-white text-xs tracking-[0] leading-[normal]">
              下一步
            </span>
          </Button>
        </div>

        <div className="flex items-center justify-center py-2">
          <div className="w-[134px] h-[5px] bg-black rounded-[100px]" />
        </div>
      </footer>

      <div className="absolute top-0 left-0 w-full h-11 flex items-center justify-between px-4">
        <time className="[font-family:'Inter',Helvetica] font-normal text-black text-sm tracking-[0] leading-[normal]">
          9:41
        </time>

        <div className="flex items-center gap-1.5">
          <img
            className="w-[17px] h-[11px]"
            alt="Cellular connection"
            src="https://c.animaapp.com/miieqry098Kjoo/img/cellular-connection.svg"
          />
          <img
            className="w-[15px] h-[11px]"
            alt="Wifi"
            src="https://c.animaapp.com/miieqry098Kjoo/img/wifi.svg"
          />
          <img
            className="w-[24px] h-[11px]"
            alt="Battery"
            src="https://c.animaapp.com/miieqry098Kjoo/img/battery.png"
          />
        </div>
      </div>
    </div>
  );
};

// 源/Apply for Settlement/src/screens/DivWrapper.vue
<template>
  <div class="div-wrapper" data-model-id="1:3900">
    <div class="rectangle" />
    <div class="frame">
      <img class="vector" alt="Vector" src="/img/vector.svg" />
    </div>
    <div class="element">
      <div class="iphone-x-status-bars-wrapper">
        <div class="iphone-x-status-bars">
          <div class="battery">
            <img class="border" alt="Border" src="/img/border.svg" />
            <img class="cap" alt="Cap" src="/img/cap.svg" />
            <img class="capacity" alt="Capacity" src="/img/capacity.svg" />
          </div>
          <img class="wifi" alt="Wifi" src="/img/wifi.svg" />
          <img class="cellular-connection" alt="Cellular connection" src="/img/cellular-connection.svg" />
          <div class="time-style">
            <div class="text-wrapper">9:41</div>
          </div>
        </div>
      </div>
    </div>
    <div class="group">
      <img class="img" alt="Vector" src="/img/vector-13.svg" />
      <div class="ellipse" />
      <div class="div" />
      <div class="ellipse-2" />
      <div class="ellipse-3" />
      <div class="ellipse-4" />
    </div>
    <div class="frame-wrapper">
      <div class="frame-2">
        <div class="frame-3">
          <div class="text-wrapper-2">申请入驻</div>
        </div>
        <div class="frame-4">
          <div class="text-wrapper-3">更多优惠政策，我们期待您的加入</div>
        </div>
      </div>
    </div>
    <div class="frame-5">
      <div class="frame-6">
        <div class="text-wrapper-4">商户入驻</div>
        <div class="frame-7">
          <div class="frame-8">
            <div class="frame-9">
              <div class="frame-10">
                <div class="frame-11">
                  <div class="text-wrapper-5">设计师入驻</div>
                  <div class="text-wrapper-6">自由美业设计师，打造个人IP品牌</div>
                </div>
                <div class="vector-wrapper">
                  <img class="vector-2" alt="Vector" src="/img/vector-4.svg" />
                </div>
              </div>
            </div>
            <img class="vector-3" alt="Vector" src="/img/vector-20-1.svg" />
          </div>
          <div class="frame-12">
            <div class="frame-9">
              <div class="frame-10">
                <div class="frame-11">
                  <div class="text-wrapper-5">实体门店入驻</div>
                  <div class="text-wrapper-6">美业线下实体门店，线上线下经营双驱动</div>
                </div>
                <div class="vector-wrapper">
                  <img class="vector-2" alt="Vector" src="/img/vector-4.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="frame-6">
        <div class="text-wrapper-4">代理商及服务合作</div>
        <div class="frame-7">
          <div class="frame-8">
            <div class="frame-9">
              <div class="frame-10">
                <div class="frame-11">
                  <div class="text-wrapper-5">渠道代理加盟</div>
                  <div class="text-wrapper-6">市场合伙人，代理收单业务，低成本轻松创业</div>
                </div>
                <div class="vector-wrapper">
                  <img class="vector-2" alt="Vector" src="/img/vector-4.svg" />
                </div>
              </div>
            </div>
            <img class="vector-3" alt="Vector" src="/img/vector-20-1.svg" />
          </div>
          <div class="frame-12">
            <div class="frame-9">
              <div class="frame-10">
                <div class="frame-11">
                  <div class="text-wrapper-5">教育拍档</div>
                  <div class="text-wrapper-6">职业教育合作，美业技能培训，职业证书认证</div>
                </div>
                <div class="vector-wrapper">
                  <img class="vector-2" alt="Vector" src="/img/vector-4.svg" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="home-indicator-wrapper">
      <div class="home-indicator" />
    </div>
    <div class="text-wrapper-7">我要合作</div>
  </div>
</template>

<script>
export default {
  name: "DivWrapper",
};
</script>

<style>
.div-wrapper {
  background-color: #f2f2f2;
  min-height: 812px;
  min-width: 375px;
  overflow: hidden;
  position: relative;
  width: 100%;
}

.div-wrapper .rectangle {
  background-color: #ffffff;
  height: 156px;
  left: 0;
  position: absolute;
  top: 0;
  width: 375px;
}

.div-wrapper .frame {
  height: 16px;
  left: 15px;
  position: absolute;
  top: 58px;
  width: 16px;
}

.div-wrapper .vector {
  height: 99.77%;
  left: 14.16%;
  position: absolute;
  top: 0;
  width: 56.08%;
}

.div-wrapper .element {
  align-items: flex-start;
  display: flex;
  height: 44px;
  left: -14px;
  min-width: 384px;
  position: absolute;
  top: 1px;
}

.div-wrapper .iphone-x-status-bars-wrapper {
  display: flex;
  height: 44px;
  width: 384px;
}

.div-wrapper .iphone-x-status-bars {
  background-image: url(../../static/img/rectangle.svg);
  background-size: 100% 100%;
  flex: 1;
  position: relative;
  width: 384.17px;
}

.div-wrapper .battery {
  height: 23.48%;
  left: 89.73%;
  position: absolute;
  top: 40.53%;
  width: 6.35%;
}

.div-wrapper .border {
  height: 100%;
  left: -2.05%;
  position: absolute;
  top: -4.84%;
  width: 88.13%;
}

.div-wrapper .cap {
  height: 38.71%;
  left: 94.43%;
  position: absolute;
  top: 30.64%;
  width: 5.57%;
}

.div-wrapper .capacity {
  height: 70.97%;
  left: 6.29%;
  position: absolute;
  top: 14.52%;
  width: 75.54%;
}

.div-wrapper .wifi {
  height: 24.92%;
  left: 84.19%;
  position: absolute;
  top: 39.39%;
  width: 4.07%;
}

.div-wrapper .cellular-connection {
  height: 24.24%;
  left: 78.31%;
  position: absolute;
  top: 40.15%;
  width: 4.53%;
}

.div-wrapper .time-style {
  display: flex;
  height: 38.64%;
  left: 9.11%;
  position: absolute;
  top: 35.23%;
  width: 7.99%;
}

.div-wrapper .text-wrapper {
  color: #000000;
  flex: 1;
  font-family: "Inter", Helvetica;
  font-size: 14px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  width: 28.69px;
}

.div-wrapper .group {
  background-color: #ffffff80;
  border-radius: 17px;
  box-shadow: 0px 0px 22.1px #0000000f;
  height: 28px;
  left: 269px;
  position: absolute;
  top: 53px;
  width: 86px;
}

.div-wrapper .img {
  height: 18px;
  left: 42px;
  position: absolute;
  top: 6px;
  width: 1px;
}

.div-wrapper .ellipse {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 16px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.div-wrapper .div {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 30px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.div-wrapper .ellipse-2 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 22px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.div-wrapper .ellipse-3 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 61px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.div-wrapper .ellipse-4 {
  border: 1px solid;
  border-color: #000000;
  border-radius: 8px;
  height: 16px;
  left: 56px;
  position: absolute;
  top: 6px;
  width: 16px;
}

.div-wrapper .frame-wrapper {
  align-items: center;
  display: flex;
  gap: 6px;
  left: 15px;
  position: absolute;
  top: 98px;
  width: 345px;
}

.div-wrapper .frame-2 {
  align-items: flex-start;
  display: inline-flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 6px;
  position: relative;
}

.div-wrapper .frame-3 {
  align-items: center;
  display: inline-flex;
  flex: 0 0 auto;
  gap: 20px;
  position: relative;
}

.div-wrapper .text-wrapper-2 {
  color: #000000;
  font-family: "PingFang SC-Semibold", Helvetica;
  font-size: 16px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  margin-top: -1.00px;
  position: relative;
  text-align: center;
  width: fit-content;
}

.div-wrapper .frame-4 {
  align-items: center;
  display: inline-flex;
  flex: 0 0 auto;
  gap: 152px;
  position: relative;
}

.div-wrapper .text-wrapper-3 {
  color: #a6a6a6;
  font-family: "PingFang SC-Regular", Helvetica;
  font-size: 12px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  margin-top: -1.00px;
  position: relative;
  width: fit-content;
}

.div-wrapper .frame-5 {
  align-items: flex-start;
  display: flex;
  flex-direction: column;
  gap: 6px;
  left: 6px;
  position: absolute;
  top: 164px;
  width: 363px;
}

.div-wrapper .frame-6 {
  align-items: flex-start;
  align-self: stretch;
  background-color: #ffffff;
  border-radius: 6px;
  display: flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 15px;
  padding: 15px;
  position: relative;
  width: 100%;
}

.div-wrapper .text-wrapper-4 {
  color: #000000;
  font-family: "PingFang SC-Semibold", Helvetica;
  font-size: 14px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  margin-top: -1.00px;
  position: relative;
  text-align: center;
  width: fit-content;
}

.div-wrapper .frame-7 {
  align-items: flex-start;
  align-self: stretch;
  display: flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 20px;
  position: relative;
  width: 100%;
}

.div-wrapper .frame-8 {
  align-items: flex-start;
  align-self: stretch;
  display: flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 15px;
  position: relative;
  width: 100%;
}

.div-wrapper .frame-9 {
  align-items: center;
  align-self: stretch;
  display: flex;
  flex: 0 0 auto;
  gap: 10px;
  justify-content: center;
  position: relative;
  width: 100%;
}

.div-wrapper .frame-10 {
  align-items: center;
  display: flex;
  flex: 1;
  flex-grow: 1;
  justify-content: space-between;
  position: relative;
}

.div-wrapper .frame-11 {
  align-items: flex-start;
  display: inline-flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 4px;
  position: relative;
}

.div-wrapper .text-wrapper-5 {
  color: #666666;
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 14px;
  font-weight: 500;
  letter-spacing: 0;
  line-height: normal;
  margin-top: -1.00px;
  position: relative;
  width: fit-content;
}

.div-wrapper .text-wrapper-6 {
  color: var(--variable-collection-a7a7a7);
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 12px;
  font-weight: 500;
  letter-spacing: 0;
  line-height: normal;
  position: relative;
  width: fit-content;
}

.div-wrapper .vector-wrapper {
  height: 14px;
  position: relative;
  transform: rotate(-90.00deg);
  width: 14px;
}

.div-wrapper .vector-2 {
  height: 50.93%;
  left: 25.72%;
  position: absolute;
  top: 5.23%;
  transform: rotate(90.00deg);
  width: 83.33%;
}

.div-wrapper .vector-3 {
  align-self: stretch;
  height: 1px;
  margin-bottom: -0.50px;
  object-fit: cover;
  position: relative;
  width: 100%;
}

.div-wrapper .frame-12 {
  align-items: flex-start;
  align-self: stretch;
  display: flex;
  flex: 0 0 auto;
  flex-direction: column;
  gap: 10px;
  position: relative;
  width: 100%;
}

.div-wrapper .home-indicator-wrapper {
  align-items: center;
  bottom: 0;
  display: flex;
  flex-direction: column;
  gap: 10px;
  height: 34px;
  justify-content: flex-end;
  left: calc(50.00% - 188px);
  padding: 8px 120px;
  position: absolute;
  width: 375px;
}

.div-wrapper .home-indicator {
  background-color: #000000;
  border-radius: 100px;
  height: 5px;
  position: relative;
  width: 134px;
}

.div-wrapper .text-wrapper-7 {
  color: #666666;
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 15px;
  font-weight: 500;
  left: 39px;
  letter-spacing: 0;
  line-height: normal;
  position: absolute;
  top: 56px;
}
</style>
