// 源/waw_style_copy_-__4wo3fs/src/screens/Screen/Screen.tsx
import React from "react";
import { Badge } from "../../components/ui/badge";
import { Tabs, TabsList, TabsTrigger } from "../../components/ui/tabs";
import { DesignSection } from "./sections/DesignSection";
import { ServiceOptionsSection } from "./sections/ServiceOptionsSection";

const statusBarIcons = [
  {
    src: "https://c.animaapp.com/mi4wi1dxPPrFZt/img/cellular-connection.svg",
    alt: "Cellular connection",
    className: "w-[4.53%] h-[24.24%]",
  },
  {
    src: "https://c.animaapp.com/mi4wi1dxPPrFZt/img/wifi.svg",
    alt: "Wifi",
    className: "w-[4.07%] h-[24.92%]",
  },
  {
    src: "https://c.animaapp.com/mi4wi1dxPPrFZt/img/battery.png",
    alt: "Battery",
    className: "w-[6.35%] h-[23.48%]",
  },
];

const tabItems = [
  { value: "designer", label: "设计师", active: true },
  { value: "service", label: "优服务", active: false },
  { value: "brand", label: "品牌馆", active: false },
];

export const Screen = (): JSX.Element => {
  return (
    <div
      className="bg-[#f2f2f2] overflow-hidden w-full min-w-[375px] min-h-screen relative flex flex-col"
      data-model-id="15:6957"
    >
      <img
        className="absolute top-0 left-0 w-[375px] h-[386px] object-cover"
        alt="Rectangle"
        src="https://c.animaapp.com/mi4wi1dxPPrFZt/img/rectangle-217.png"
      />

      <img
        className="absolute top-[285px] left-0 w-[375px] h-[1118px] object-cover"
        alt="Group"
        src="https://c.animaapp.com/mi4wi1dxPPrFZt/img/group-33.png"
      />

      <header className="relative z-10 w-full">
        <nav className="w-[102.45%] h-[44px] -ml-[3.69%] flex">
          <div className="flex-1 w-[384.17px] relative">
            <div className="absolute top-[35.23%] left-[9.11%] [font-family:'Inter',Helvetica] font-normal text-black text-sm tracking-[0] leading-[normal]">
              9:41
            </div>
            <div className="absolute top-[39.39%] right-[3.85%] flex items-center gap-[15px]">
              {statusBarIcons.map((icon, index) => (
                <img
                  key={index}
                  className={icon.className}
                  alt={icon.alt}
                  src={icon.src}
                />
              ))}
            </div>
          </div>
        </nav>

        <div className="relative mt-[-13px] px-[15px] py-[31px] flex items-center justify-between">
          <div className="flex items-center gap-6">
            <button className="w-4 h-4 flex items-center justify-center">
              <img
                className="w-4 h-4"
                alt="Back"
                src="https://c.animaapp.com/mi4wi1dxPPrFZt/img/frame-4.svg"
              />
            </button>
            <div className="[font-family:'DIN_Black-Regular',Helvetica] font-normal text-white text-[15px] tracking-[0] leading-[normal]">
              美发
            </div>
          </div>

          <img
            className="w-32 h-[72px]"
            alt="Group"
            src="https://c.animaapp.com/mi4wi1dxPPrFZt/img/group-8.png"
          />
        </div>

        <div className="relative px-[15px] -mt-[21px]">
          <Badge className="bg-[#00000066] hover:bg-[#00000066] text-[#e6e6e6] rounded-[26px] h-[30px] px-2.5 py-1 border-0">
            <img
              className="w-[18px] h-[18px] mr-0.5"
              alt="Frame"
              src="https://c.animaapp.com/mi4wi1dxPPrFZt/img/frame-1.svg"
            />
            <span className="[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[11px]">
              设计师
            </span>
          </Badge>
        </div>
      </header>

      <div className="relative z-10 mt-[219px]">
        <Tabs defaultValue="designer" className="w-full">
          <TabsList className="w-full h-auto bg-transparent border-0 rounded-none p-0 grid grid-cols-3 gap-0">
            {tabItems.map((tab) => (
              <TabsTrigger
                key={tab.value}
                value={tab.value}
                className="relative data-[state=active]:bg-transparent data-[state=active]:shadow-none rounded-none border-0 px-0 py-0 h-auto"
              >
                <div className="flex flex-col items-center gap-[3px] py-2">
                  <span
                    className={`${
                      tab.active
                        ? "[font-family:'DIN_Black-Regular',Helvetica] font-normal text-black"
                        : "[font-family:'PingFang_SC-Regular',Helvetica] font-normal text-[#666666]"
                    } text-sm tracking-[0] leading-[normal]`}
                  >
                    {tab.label}
                  </span>
                  {tab.active && (
                    <img
                      className="w-[17px] h-[5px]"
                      alt="Active indicator"
                      src="https://c.animaapp.com/mi4wi1dxPPrFZt/img/rectangle-215.svg"
                    />
                  )}
                </div>
              </TabsTrigger>
            ))}
          </TabsList>
        </Tabs>
      </div>

      <main className="relative z-10 flex-1 flex flex-col">
        <DesignSection />
        <ServiceOptionsSection />
      </main>

      <footer className="relative z-10 flex items-center justify-center px-[120px] py-2 h-[34px] mt-auto">
        <div className="w-[134px] h-[5px] bg-black rounded-[100px]" />
      </footer>
    </div>
  );
};

// 源/MyShoucang/src/screens/Screen.vue
<template>
  <div class="screen" data-model-id="1:3382">
    <div class="rectangle-2" />
    <div class="text-wrapper-7">我的收藏</div>
    <div class="vector-wrapper">
      <img class="vector" alt="Vector" src="/img/vector.svg" />
    </div>
    <div class="element">
      <div class="iphone-x-status-bars-wrapper">
        <div class="iphone-x-status-bars">
          <div class="battery">
            <img class="border" alt="Border" src="/img/border.svg" />
            <img class="cap" alt="Cap" src="/img/cap.svg" />
            <img class="capacity" alt="Capacity" src="/img/capacity.svg" />
          </div>
          <img class="wifi" alt="Wifi" src="/img/wifi.svg" />
          <img class="cellular-connection" alt="Cellular connection" src="/img/cellular-connection.svg" />
          <div class="time-style">
            <div class="text-wrapper-8">9:41</div>
          </div>
        </div>
      </div>
    </div>
    <div class="group">
      <img class="img" alt="Vector" src="/img/vector-13.svg" />
      <div class="ellipse" />
      <div class="ellipse-2" />
      <div class="ellipse-3" />
      <div class="ellipse-4" />
      <div class="ellipse-5" />
    </div>
    <div class="home-indicator-wrapper">
      <div class="home-indicator" />
    </div>
    <div class="frame-2">
      <Frame class="frame-1852" />
      <Frame class="frame-1852" />
      <Frame class="frame-1852" />
      <Frame class="frame-1852" />
    </div>
  </div>
</template>

<script>
import Frame from "../components/Frame.vue";

export default {
  name: "Screen",
  components: {
    Frame
  }
};
</script>

<style>
.screen {
  background-color: #f2f2f2;
  min-height: 812px;
  min-width: 375px;
  overflow: hidden;
  position: relative;
  width: 100%;
}

.screen .rectangle-2 {
  background-color: #ffffff;
  height: 88px;
  left: 0;
  position: absolute;
  top: 0;
  width: 375px;
}

.screen .text-wrapper-7 {
  color: #333333;
  font-family: "PingFang SC-Medium", Helvetica;
  font-size: 16px;
  font-weight: 500;
  left: calc(50.00% - 32px);
  letter-spacing: 0;
  line-height: normal;
  position: absolute;
  text-align: center;
  top: 55px;
}

.screen .vector-wrapper {
  height: 16px;
  left: 15px;
  position: absolute;
  top: 58px;
  width: 16px;
}

.screen .vector {
  height: 99.77%;
  left: 14.16%;
  position: absolute;
  top: 0;
  width: 56.08%;
}

.screen .element {
  align-items: flex-start;
  display: flex;
  height: 44px;
  left: -14px;
  min-width: 384px;
  position: absolute;
  top: 1px;
}

.screen .iphone-x-status-bars-wrapper {
  display: flex;
  height: 44px;
  width: 384px;
}

.screen .iphone-x-status-bars {
  background-image: url(../../static/img/rectangle.svg);
  background-size: 100% 100%;
  flex: 1;
  position: relative;
  width: 384.17px;
}

.screen .battery {
  height: 23.48%;
  left: 89.73%;
  position: absolute;
  top: 40.53%;
  width: 6.35%;
}

.screen .border {
  height: 100%;
  left: -2.05%;
  position: absolute;
  top: -4.84%;
  width: 88.13%;
}

.screen .cap {
  height: 38.71%;
  left: 94.43%;
  position: absolute;
  top: 30.64%;
  width: 5.57%;
}

.screen .capacity {
  height: 70.97%;
  left: 6.29%;
  position: absolute;
  top: 14.52%;
  width: 75.54%;
}

.screen .wifi {
  height: 24.92%;
  left: 84.19%;
  position: absolute;
  top: 39.39%;
  width: 4.07%;
}

.screen .cellular-connection {
  height: 24.24%;
  left: 78.31%;
  position: absolute;
  top: 40.15%;
  width: 4.53%;
}

.screen .time-style {
  display: flex;
  height: 38.64%;
  left: 9.11%;
  position: absolute;
  top: 35.23%;
  width: 7.99%;
}

.screen .text-wrapper-8 {
  color: #000000;
  flex: 1;
  font-family: "Inter", Helvetica;
  font-size: 14px;
  font-weight: 400;
  letter-spacing: 0;
  line-height: normal;
  width: 28.69px;
}

.screen .group {
  background-color: #ffffff80;
  border-radius: 17px;
  box-shadow: 0px 0px 22.1px #0000000f;
  height: 28px;
  left: 269px;
  position: absolute;
  top: 53px;
  width: 86px;
}

.screen .img {
  height: 18px;
  left: 42px;
  position: absolute;
  top: 6px;
  width: 1px;
}

.screen .ellipse {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 16px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.screen .ellipse-2 {
  background-color: #000000;
  border-radius: 1.5px;
  height: 3px;
  left: 30px;
  position: absolute;
  top: 13px;
  width: 3px;
}

.screen .ellipse-3 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 22px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.screen .ellipse-4 {
  background-color: #000000;
  border-radius: 3px;
  height: 6px;
  left: 61px;
  position: absolute;
  top: 11px;
  width: 6px;
}

.screen .ellipse-5 {
  border: 1px solid;
  border-color: #000000;
  border-radius: 8px;
  height: 16px;
  left: 56px;
  position: absolute;
  top: 6px;
  width: 16px;
}

.screen .home-indicator-wrapper {
  align-items: center;
  bottom: 0;
  display: flex;
  flex-direction: column;
  gap: 10px;
  height: 34px;
  justify-content: flex-end;
  left: calc(50.00% - 188px);
  padding: 8px 120px;
  position: absolute;
  width: 375px;
}

.screen .home-indicator {
  background-color: #000000;
  border-radius: 100px;
  height: 5px;
  position: relative;
  width: 134px;
}

.screen .frame-2 {
  align-items: flex-start;
  display: flex;
  flex-direction: column;
  gap: 8px;
  left: 6px;
  position: absolute;
  top: 96px;
  width: 363px;
}

.screen .frame-1852 {
  align-self: stretch !important;
  flex: 0 0 auto !important;
  width: 100% !important;
}
</style>
